<?php
/**
 * Moon Dental · 치과사전 3차 대량 확장 시드 (600+ 개 추가)
 *
 *  v3.35.3 · 사용자 요청 · 총 1000+ 용어 목표.
 *  중복 스킵 → 신규만 추가.
 *
 * @package moondental-child
 */

if ( ! defined( 'ABSPATH' ) ) exit;

function moondental_encyclopedia_seed_data_v3353() {
	return array(

		/* ==================== 임플란트 확장 (100+) ==================== */
		array( '노벨 바이오케어', 'implant', '스웨덴 발생 · 세계 최초 임플란트 브랜드', '<p>Nobel Biocare. Brånemark이 창립한 <strong>세계 최초 상용 임플란트</strong>. 노벨 액티브·리플레이스 시스템.</p>' ),
		array( '노벨 액티브', 'implant', '노벨 바이오케어의 대표 시스템', '<p>Nobel Active. <strong>가변형 나사산</strong>으로 초기 고정력 우수. 즉시 하중에 유리.</p>' ),
		array( '노벨 리플레이스', 'implant', '노벨의 트라이-채널 시스템', '<p>Nobel Replace. Tri-Channel 연결부. <strong>안정된 골유착·다양한 지대주</strong>.</p>' ),
		array( '브레네막', 'implant', '임플란트 창시자 · 골유착 발견', '<p>Per-Ingvar Brånemark. <strong>1965년 골유착 발견</strong>. 현대 임플란트의 아버지.</p>' ),
		array( '짐머 바이오멧', 'implant', '미국 대표 임플란트 · Tapered Screw-Vent', '<p>Zimmer Biomet. <strong>Tapered Screw-Vent·Trabecular Metal</strong> 시스템. 미국 3대 브랜드.</p>' ),
		array( '덴티움', 'implant', '국내 프리미엄 임플란트', '<p>Dentium. Superline·NR Line 등. <strong>국산 프리미엄 브랜드</strong>. 해외 수출 활발.</p>' ),
		array( '네오바이오텍', 'implant', '국산 임플란트 · IS/CMI 시스템', '<p>NeoBiotech. <strong>IS-III·CMI IS-III</strong>. 자체 개발 GBR 키트.</p>' ),
		array( 'HiPO 임플란트', 'implant', '국산 임플란트 브랜드', '<p>HiPO. 국내 <strong>중견 브랜드</strong>. 다양한 라인업.</p>' ),
		array( '오스템 TS', 'implant', '오스템의 표준·대중 라인', '<p>Osstem TS. <strong>가장 대중적인 라인</strong>. TSII·TSIII SA·TSIII CA 등.</p>' ),
		array( '오스템 SS', 'implant', '오스템의 상급 라인 · 표면 처리 강화', '<p>Osstem SS. <strong>Sandblasted Surface</strong>. TS보다 골유착 우수.</p>' ),
		array( '오스템 KS', 'implant', '오스템의 최상위 프리미엄 라인', '<p>Osstem KS. <strong>내면 접촉 면적·결합 깊이 강화</strong>. 문치과병원 사용.</p>' ),
		array( '오스템 GS', 'implant', '오스템의 심미부용 임플란트', '<p>Osstem GS. <strong>Bone Level 디자인</strong>. 심미 부위에 적합.</p>' ),
		array( '스트라우만 BLX', 'implant', '스트라우만 최신 즉시 하중용', '<p>Straumann BLX. <strong>즉시 하중 최적화</strong> 가변 나사산. 최신 시스템.</p>' ),
		array( '스트라우만 BLT', 'implant', '스트라우만 테이퍼드 라인', '<p>Straumann BLT. Bone Level Tapered. <strong>골질 부족·즉시 식립</strong>에 유리.</p>' ),
		array( '스트라우만 SLA', 'implant', '스트라우만 표면 처리 표준', '<p>Sandblasted, Large-grit, Acid-etched. 30년+ <strong>임상 실적 표준 표면</strong>.</p>' ),
		array( '스트라우만 SLActive', 'implant', 'SLA + 초친수성 강화', '<p>SLActive. SLA에 <strong>초친수성 활성화</strong> 추가. 골유착 3~4주로 단축.</p>' ),
		array( '스트라우만 Roxolid', 'implant', '티타늄-지르코늄 합금 임플란트', '<p>Straumann Roxolid. <strong>Ti + Zr 합금</strong>. 순수 티타늄보다 강도 우수, 좁은 지름 사용 가능.</p>' ),
		array( '메가젠 AnyRidge', 'implant', '가변 나사산 · 초기 고정력 최적화', '<p>MEGAGEN AnyRidge. <strong>Knife-thread</strong> 가변 나사산. 다양한 골질에 적응.</p>' ),
		array( '메가젠 ARi Cuff', 'implant', '연조직 친화 · 심미부용', '<p>MEGAGEN ARi Cuff. 연조직 친화적. <strong>주변 조직 손상 최소</strong>.</p>' ),
		array( '메가젠 BD Cuff', 'implant', '앞니 임플란트 심미 최적화', '<p>BD Cuff. 골재생 속도 향상. <strong>앞니 심미 케이스</strong>에 최적화.</p>' ),
		array( '짧은 임플란트', 'implant', '길이 6~8mm의 짧은 픽스처', '<p>Short Implant. <strong>골량 부족 시 사용</strong>. 상악동 거상술 회피.</p>' ),
		array( '좁은 임플란트', 'implant', '지름 3mm 이하 · 좁은 부위용', '<p>Narrow Implant. 하악 앞니 등 <strong>좁은 부위에 사용</strong>. 골이식 최소화.</p>' ),
		array( '넓은 임플란트', 'implant', '지름 5~6mm · 큰 어금니용', '<p>Wide Implant. <strong>큰 어금니 부위</strong>. 즉시 발치·즉시 식립에 활용.</p>' ),
		array( 'Zygomatic 임플란트', 'implant', '광대뼈 고정형 초장기 임플란트', '<p>Zygomatic Implant. 상악 골량 부족·<strong>All-on-4 지지용</strong>. 광대뼈에 45mm+ 픽스처 식립.</p>' ),
		array( 'All-on-6', 'implant', '전악 6개 임플란트 지지 보철', '<p>All-on-6. All-on-4보다 <strong>안정성 강화</strong>. 6개 임플란트로 전악 지지.</p>' ),
		array( '골 밀도 D1', 'implant', '가장 단단한 골 (하악 전방)', '<p>D1 Bone. <strong>피질골 두꺼움</strong>. 하악 전치부 흔함. 골유착 안정적.</p>' ),
		array( '골 밀도 D2', 'implant', '두꺼운 피질골 + 조밀한 해면골', '<p>D2 Bone. <strong>이상적 임플란트 골질</strong>. 하악 후방 흔함.</p>' ),
		array( '골 밀도 D3', 'implant', '얇은 피질골 + 조밀 해면골', '<p>D3 Bone. 상악 전방·<strong>일반적</strong>. 초기 고정력 주의.</p>' ),
		array( '골 밀도 D4', 'implant', '피질골 얇음 + 성긴 해면골', '<p>D4 Bone. <strong>상악 후방</strong> 흔함. 골유착 오래 걸림. 즉시 하중 어려움.</p>' ),
		array( '스캔 바디', 'implant', '디지털 인상용 임플란트 부품', '<p>Scan Body. 임플란트에 연결해 <strong>구강 스캐너로 위치 인식</strong>.</p>' ),
		array( '스캔 어버트먼트', 'implant', '스캔 바디와 동일', '<p>디지털 인상 시 임플란트 위치를 <strong>스캐너에 인식시키는</strong> 부품.</p>' ),
		array( '인상 코핑', 'implant', '실리콘 인상용 임플란트 부품', '<p>Impression Coping. 실리콘 인상 시 <strong>임플란트 위치 전달</strong>.</p>' ),
		array( '오픈 트레이 인상', 'implant', '인상 트레이에 구멍 뚫는 방식', '<p>Open Tray. 트레이에 <strong>구멍</strong>을 뚫어 임프레션 코핑 나사를 통과. 정확도 우수.</p>' ),
		array( '클로즈드 트레이 인상', 'implant', '스탠다드 트레이 사용 인상', '<p>Closed Tray. <strong>일반 트레이</strong> 사용. 간편하지만 오차 가능.</p>' ),
		array( '삽입 토크', 'implant', '임플란트 식립 시 회전력', '<p>Insertion Torque. <strong>Ncm 단위</strong>. 30Ncm 이상이면 즉시 하중 가능성.</p>' ),
		array( '토크 렌치', 'implant', '지대주 나사 조임용 정밀 렌치', '<p>Torque Wrench. <strong>규정 토크</strong>로 나사 조임. 나사 풀림 방지.</p>' ),
		array( '역행성 근관치료', 'implant', '치근 끝을 절제 후 봉쇄', '<p>Retrograde Endo. 일반 근관치료 실패 시 <strong>치근 끝을 외과적 제거·MTA 봉쇄</strong>.</p>' ),
		array( '치조제 확장술', 'implant', '좁은 잇몸뼈를 벌려 임플란트 공간 확보', '<p>Ridge Splitting. <strong>얇은 치조골</strong>을 종축으로 벌려 임플란트 식립 가능하게.</p>' ),
		array( '연조직 이식', 'implant', '임플란트 주변 잇몸 두께 증대', '<p>Soft Tissue Graft. 임플란트 주변 <strong>부착치은 확보</strong>. 장기 안정성 향상.</p>' ),
		array( '이머전스 프로파일', 'implant', '임플란트-크라운 경계의 잇몸 형태', '<p>Emergence Profile. 잇몸 라인이 크라운으로 <strong>자연스럽게 이어지는 형태</strong>. 심미의 핵심.</p>' ),
		array( '지대주 각도', 'implant', '15°·20°·25°·30° 각도 조절 지대주', '<p>Angulated Abutment. 임플란트 축과 <strong>보철 방향 차이를 보상</strong>.</p>' ),
		array( '멀티유닛 어버트먼트', 'implant', 'All-on-4 등 다수 임플란트 연결용', '<p>Multi-Unit Abutment. 4~6개 임플란트를 <strong>연결한 보철에 사용</strong>.</p>' ),
		array( '틸티드 임플란트', 'implant', '기울여 식립하는 임플란트', '<p>Tilted Implant. All-on-4의 <strong>후방 45°</strong> 임플란트. 상악동·신경 회피.</p>' ),
		array( '즉시 로딩', 'implant', '식립 당일 임시 보철', '<p>Immediate Loading. <strong>초기 고정력 35Ncm+</strong> 필요. 심미부에 유리.</p>' ),
		array( '지연 로딩', 'implant', '골유착 후 3~6개월 뒤 보철', '<p>Delayed Loading. 전통적 방식. <strong>안전성 최고</strong>.</p>' ),
		array( '조기 로딩', 'implant', '식립 후 1~2개월 뒤 보철', '<p>Early Loading. 즉시와 지연 중간. <strong>1~2개월</strong> 후 최종 보철.</p>' ),
		array( '임플란트 실패율', 'implant', '5년 5% · 10년 10% 내외', '<p>5년 성공률 95%+, 10년 성공률 90%+. <strong>흡연·당뇨·주위염</strong>이 주 실패 원인.</p>' ),
		array( '재식립 성공률', 'implant', '실패 후 재식립 성공률 80% 내외', '<p>실패 임플란트 제거 후 <strong>골이식·회복 → 재식립</strong>. 성공률 80%+.</p>' ),
		array( '임플란트 유지관리', 'implant', '평생 6개월 정기 검진', '<p>Maintenance. <strong>스케일링·프로빙·X-ray</strong>. 주위염 조기 발견.</p>' ),
		array( '임플란트 통증', 'implant', '식립 후 2~3일 정도의 정상 통증', '<p>수술 후 정상. <strong>진통제로 조절</strong>. 1주 후 지속 시 감염 의심.</p>' ),
		array( '임플란트 붓기', 'implant', '식립 후 2~4일 절정 후 감소', '<p>수술 정상 반응. <strong>냉찜질·항염제·베개 높임</strong>으로 완화.</p>' ),
		array( '임플란트 감염', 'implant', '식립 후 세균 감염', '<p>초기 감염 → 골유착 실패 위험. 항생제·<strong>세척으로 대응</strong>.</p>' ),
		array( '임플란트 재수술 성공률', 'implant', '2차 재수술 성공률 80~85%', '<p>초회 실패 후 <strong>재식립 성공률 80~85%</strong>. 3회 시도는 신중히 결정.</p>' ),
		array( '임플란트 골 두께', 'implant', '식립을 위한 최소 1mm+ 협측 골', '<p>Buccal Bone Thickness. 안정적 심미와 <strong>골 흡수 방지</strong>를 위해 1mm+ 필요.</p>' ),
		array( '골 정출 후 임플란트', 'implant', '골 정출된 부위의 재구성', '<p>골이식 등으로 <strong>재구성 후</strong> 임플란트 식립.</p>' ),
		array( '슈나이더 막', 'implant', '상악동 점막 · 거상술 시 유지 중요', '<p>Schneiderian Membrane. 상악동 <strong>점막층</strong>. 거상술 시 파열 예방이 관건.</p>' ),
		array( '상악동 점막 열개', 'implant', '거상술 중 점막이 찢어지는 합병증', '<p>Sinus Membrane Perforation. <strong>콜라겐 멤브레인·봉합</strong>으로 처치.</p>' ),
		array( '치조제 재구성', 'implant', '심하게 흡수된 잇몸뼈 재건', '<p>Alveolar Reconstruction. <strong>블록골 이식·GBR</strong> 등으로 재건.</p>' ),
		array( '블록골 이식', 'implant', '자가 블록골로 큰 골 결손 재건', '<p>Block Bone Graft. <strong>하악 지대·이부</strong>에서 채취해 큰 결손 재건.</p>' ),
		array( '악골 융합', 'implant', '유아기 상하악 융합 상태', '<p>드문 선천성 이상. <strong>수술적 분리</strong> 필요.</p>' ),
		array( '지대주 나사', 'implant', '지대주와 픽스처를 연결하는 나사', '<p>Abutment Screw. <strong>정확한 토크</strong>로 조임. 20~35Ncm 규정치.</p>' ),
		array( '나사 파절', 'implant', '지대주 나사가 부러진 합병증', '<p>Screw Fracture. 반복 스트레스·과부하 원인. <strong>제거 후 재조립</strong>.</p>' ),
		array( '픽스처-지대주 미스핏', 'implant', '적합도 불량으로 인한 만성 문제', '<p>Misfit. 나사 풀림·<strong>골 흡수·주위염</strong> 원인. 재제작 필요.</p>' ),
		array( '임플란트 마진', 'implant', '임플란트-크라운 경계', '<p>Implant Margin. <strong>변연 적합도</strong>가 주위염 예방에 중요.</p>' ),
		array( '임플란트 시멘트 잔류', 'implant', '접착 시멘트가 잇몸 아래 남음', '<p>Cement Retention. 잇몸염·<strong>주위염 원인</strong>. 스크류 유지가 안전.</p>' ),
		array( '임플란트 스캐너', 'implant', '임플란트 진단·계획 전용 소프트웨어', '<p>Implant Planning Software. <strong>3D CBCT 분석·수술 가이드 제작</strong>. R2GATE·SimPlant.</p>' ),
		array( '임플란트 시술 시간', 'implant', '식립 1~2시간 · 회복 3~6개월', '<p>단일 임플란트 <strong>30~60분</strong>. 골이식 병행 시 1~2시간.</p>' ),
		array( '임플란트 회복 기간', 'implant', '골유착 3~6개월', '<p>하악 3~4개월·상악 4~6개월. <strong>골이식 병행 시 6~9개월</strong>.</p>' ),
		array( '임플란트 조기 실패', 'implant', '1년 내 실패 · 주로 골유착 실패', '<p>Early Failure. <strong>초기 감염·과부하·환자 관리 소홀</strong>이 원인.</p>' ),
		array( '임플란트 후기 실패', 'implant', '1년 이후 실패 · 주로 주위염', '<p>Late Failure. <strong>임플란트 주위염·과부하</strong>가 원인.</p>' ),
		array( '픽스처 나사산', 'implant', '임플란트 표면의 나선형 요철', '<p>Implant Thread. 초기 <strong>골 고정력</strong> 결정. 다양한 디자인.</p>' ),
		array( 'V-thread', 'implant', 'V자형 나사산 · 표준', '<p>가장 흔한 디자인. <strong>균등한 응력 분포</strong>.</p>' ),
		array( 'Buttress Thread', 'implant', '한쪽 방향 강화 나사산', '<p>Buttress Thread. <strong>일방향 응력</strong>에 강함. 즉시 하중용.</p>' ),
		array( '골 관통형 임플란트', 'implant', 'Basal Implant · 특수 골관통형', '<p>Basal Implant. <strong>피질골 관통</strong> 특수 임플란트. 즉시 하중.</p>' ),
		array( '임플란트 하부 구조', 'implant', 'All-on-4의 바 프레임', '<p>Bar Framework. All-on-4·전악 임플란트의 <strong>금속 프레임</strong>. 보철 지지.</p>' ),
		array( '픽스처-지대주 연결부', 'implant', '외부·내부·모스 테이퍼', '<p>External Hex·Internal Hex·<strong>Morse Taper</strong>. 연결 방식별 특징.</p>' ),
		array( '외부 육각 연결', 'implant', 'External Hex · 초기 임플란트 표준', '<p>External Hex. 초기 브레네막·<strong>노벨 리플레이스</strong> 등에 사용.</p>' ),
		array( '내부 육각 연결', 'implant', 'Internal Hex · 현대 표준', '<p>Internal Hex. <strong>대부분 현대 임플란트</strong>. 안정적·심미성.</p>' ),
		array( '모스 테이퍼', 'implant', 'Morse Taper · 원뿔 연결부', '<p>Morse Taper. <strong>원뿔형 마찰 결합</strong>. 미세 갭 최소·마이크로유동 없음.</p>' ),
		array( 'AnkyLos', 'implant', '독일 짐머 · 모스 테이퍼 대표', '<p>Ankylos. Dentsply Sirona · <strong>모스 테이퍼 원조</strong>. 조직 안정성 우수.</p>' ),
		array( 'PDLLA', 'implant', '생분해성 폴리머 · 임플란트 코팅', '<p>Poly D,L-Lactic Acid. 생분해성. <strong>서방형 약물 전달</strong>에 활용.</p>' ),
		array( '커스텀 힐링 어버트먼트', 'implant', '환자 맞춤 힐링 지대주', '<p>Custom Healing Abutment. 최종 <strong>보철 형태와 유사</strong>. 잇몸 형성 최적화.</p>' ),
		array( '지대주 프로파일', 'implant', '지대주의 잇몸 접촉면 형태', '<p>Abutment Profile. <strong>Concave·Straight·Convex</strong>. 잇몸 두께에 맞춤.</p>' ),

		/* ==================== 교정 확장 (80+) ==================== */
		array( '3M Clarity', 'ortho', '3M의 심미 세라믹 브라켓', '<p>3M Clarity. <strong>Advanced Ceramic</strong> 브라켓. 자가결찰 SL 모델 있음.</p>' ),
		array( 'Damon Clear', 'ortho', '데이몬의 투명 세라믹 라인', '<p>Damon Clear. <strong>투명 세라믹</strong>. 데이몬 시스템의 심미 옵션.</p>' ),
		array( 'Damon Q2', 'ortho', '데이몬의 최신 자가결찰 시스템', '<p>Damon Q2. <strong>슬라이드 도어</strong>·마찰 감소·이동 속도 향상.</p>' ),
		array( 'Speed System', 'ortho', 'Strite Industries의 자가결찰 브라켓', '<p>Speed System. 캐나다 개발. <strong>가장 작은 자가결찰</strong>.</p>' ),
		array( 'In-Ovation', 'ortho', 'Dentsply GAC의 자가결찰 시스템', '<p>In-Ovation R·C·L. 액티브 자가결찰.</p>' ),
		array( '인비절라인 Comprehensive', 'ortho', '전악 교정 · 무제한 얼라이너', '<p>Invisalign Comprehensive. <strong>전체 교정</strong>. 무제한 리파인먼트.</p>' ),
		array( '인비절라인 Lite', 'ortho', '경증 케이스 · 14세트 이하', '<p>Invisalign Lite. <strong>경증 부정교합</strong>. 최대 14세트.</p>' ),
		array( '인비절라인 Express', 'ortho', '5세트 · 3~5개월 완료', '<p>Invisalign Express. <strong>매우 경미한 케이스</strong>. 5세트로 완료.</p>' ),
		array( '인비절라인 First', 'ortho', '어린이용 얼라이너', '<p>Invisalign First. <strong>혼합치열기</strong> 아동용. 성장 조절.</p>' ),
		array( 'Roth 프리스크립션', 'ortho', 'Ronald Roth의 브라켓 각도 설정', '<p>Roth Prescription. 1970년대 개발. <strong>가장 널리 사용</strong>되는 프리스크립션.</p>' ),
		array( 'MBT 프리스크립션', 'ortho', 'McLaughlin-Bennett-Trevisi 설정', '<p>MBT. <strong>슬라이딩 역학</strong>에 최적화. Roth보다 저마찰.</p>' ),
		array( 'Andrews 프리스크립션', 'ortho', 'Lawrence Andrews의 원조 스트레이트 와이어', '<p>Andrews Straight Wire. <strong>스트레이트 와이어 원조</strong>. 6가지 열쇠 이론.</p>' ),
		array( '앙글 분류', 'ortho', 'Edward Angle의 부정교합 분류', '<p>Angle Classification. <strong>Class I·II·III</strong>. 상하악 어금니 관계로 분류.</p>' ),
		array( 'ANB 각도', 'ortho', '두부방사선 상 상악·하악 각도', '<p>ANB Angle. 정상 2±2°. <strong>Class II는 4°+, Class III는 0° 미만</strong>.</p>' ),
		array( 'SNA 각도', 'ortho', '상악 전방 위치 각도', '<p>SNA. 정상 82±2°. <strong>상악 전방 위치</strong>의 지표.</p>' ),
		array( 'SNB 각도', 'ortho', '하악 전방 위치 각도', '<p>SNB. 정상 80±2°. <strong>하악 전방 위치</strong>의 지표.</p>' ),
		array( '오버젯', 'ortho', '위·아래 앞니 수평 거리', '<p>Overjet. 정상 2~4mm. <strong>돌출입은 커지고 반대교합은 음수</strong>.</p>' ),
		array( '오버바이트', 'ortho', '위·아래 앞니 수직 겹침', '<p>Overbite. 정상 2~4mm. <strong>과개교합 크고 개방교합 음수</strong>.</p>' ),
		array( '크로스바이트', 'ortho', '반대교합 · 위 치아가 아래 치아 뒤', '<p>Crossbite. 전방·후방·<strong>편측</strong> 크로스바이트로 구분.</p>' ),
		array( '씨저스바이트', 'ortho', '위·아래 어금니가 가위처럼 엇갈림', '<p>Scissors Bite. 상하 어금니가 <strong>수평으로 만나지 않고 엇갈림</strong>.</p>' ),
		array( '전방 크로스바이트', 'ortho', '앞니 반대교합', '<p>Anterior Crossbite. 위 앞니가 <strong>아래 앞니 뒤</strong>. 주걱턱 초기.</p>' ),
		array( '측방 크로스바이트', 'ortho', '어금니 반대교합', '<p>Posterior Crossbite. 위 어금니가 <strong>아래 어금니 안쪽</strong>. 상악 좁음 원인.</p>' ),
		array( '이차 총생', 'ortho', '성인기 지속되는 앞니 겹침', '<p>Adult Crowding. 나이 들며 <strong>앞니가 다시 겹치는 현상</strong>. 리테이너 부실.</p>' ),
		array( '립 컴피턴시', 'ortho', '입술 자연 폐쇄 상태', '<p>Lip Competence. 편안한 상태에서 <strong>입술이 자연스럽게 닫히는지</strong>.</p>' ),
		array( '립 이중 성장', 'ortho', '뇌하수체 이상으로 인한 성장', '<p>드물게 발생. 성장기 <strong>과도한 골격 성장</strong>.</p>' ),
		array( 'TAD', 'ortho', 'Temporary Anchorage Device · 임시 고정원', '<p>미니 스크류·미니 플레이트. <strong>강한 앵커리지</strong> 제공.</p>' ),
		array( '얼라이너 착용 시간', 'ortho', '하루 20~22시간 필수', '<p>Wear Time. <strong>20시간 이상</strong>. 식사·양치 외 착용.</p>' ),
		array( '얼라이너 교체 주기', 'ortho', '보통 1~2주 간격', '<p>Aligner Change. 1주 or 2주. <strong>치아 이동 속도</strong>에 맞춤.</p>' ),
		array( '얼라이너 세척', 'ortho', '전용 클리너·부드러운 칫솔', '<p>부드러운 <strong>칫솔·전용 클리너</strong>. 뜨거운 물·치약 금지 (변형).</p>' ),
		array( '얼라이너 부작용', 'ortho', '초기 발음·통증·건조', '<p>초기 1~2주 <strong>발음 어색·잇몸 자극</strong>. 대부분 적응됨.</p>' ),
		array( '리테이너 종류', 'ortho', '가철식 vs 고정식', '<p>Hawley·Essix(투명)·<strong>고정식(와이어 접착)</strong>.</p>' ),
		array( '리테이너 착용 기간', 'ortho', '최소 1년 · 평생 야간 착용 권장', '<p>초기 1년 <strong>주간 착용</strong>, 이후 야간 착용 평생.</p>' ),
		array( '재교정', 'ortho', '리테이너 미착용 등으로 재교정', '<p>Re-Treatment. 대부분 <strong>리테이너 미착용</strong>이 원인. 재교정 시 짧게 완료 가능.</p>' ),
		array( '조기 교정 1단계', 'ortho', '6~10세 · 골격 문제 예방', '<p>Phase I. 반대교합·<strong>좁은 상악·나쁜 습관</strong> 교정.</p>' ),
		array( '조기 교정 2단계', 'ortho', '11세~ 영구치 완료 후 · 최종 정렬', '<p>Phase II. 영구치 완료 후 <strong>브라켓·얼라이너</strong>로 최종 배열.</p>' ),
		array( '성인 교정', 'ortho', '성인기 시작하는 교정', '<p>Adult Orthodontics. 성장 완료 · <strong>발치·얼라이너·설측</strong>이 흔한 선택.</p>' ),
		array( '청소년 교정', 'ortho', '10대 · 가장 활발한 성장기 교정', '<p>Adolescent Orthodontics. <strong>골격 반응 우수</strong>. 협조 필요.</p>' ),
		array( '노인 교정', 'ortho', '고령자도 가능 · 잇몸 건강 필수', '<p>Senior Orthodontics. <strong>치주 건강 확보</strong>가 우선. 얼라이너·설측 선호.</p>' ),
		array( '엑스트루전', 'ortho', '치아 정출 · 밖으로 이동', '<p>Extrusion. <strong>치아를 잇몸 밖으로</strong> 끌어내는 교정 이동.</p>' ),
		array( '인트루전', 'ortho', '치아 함입 · 안으로 이동', '<p>Intrusion. <strong>치아를 잇몸 안으로</strong> 미는 교정 이동. 미니 스크류 활용.</p>' ),
		array( '틸팅', 'ortho', '치아 축을 기울이는 이동', '<p>Tipping. 치아 <strong>축을 기울이는</strong> 가장 간단한 이동.</p>' ),
		array( '토크', 'ortho', '치근을 이동시키는 회전력', '<p>Torque. 치관은 그대로·<strong>치근을 이동</strong>. 3차원 이동에 필수.</p>' ),
		array( '평행 이동', 'ortho', '치아 전체가 평행하게 이동', '<p>Bodily Movement. 치관·치근이 <strong>동시에</strong> 같은 방향으로 이동.</p>' ),
		array( '회전 교정', 'ortho', '치아 축을 중심으로 회전', '<p>Rotation. 회전된 치아를 <strong>정상 축으로 회전</strong>.</p>' ),
		array( '와이어 굽힘', 'ortho', '와이어에 특정 각도·굴곡 부여', '<p>Bending. 개별 치아 이동을 위한 <strong>2·3차 굴곡</strong>.</p>' ),
		array( '치아 이동 원리', 'ortho', '치근 주변 뼈의 재흡수·재형성', '<p>Bone Remodeling. 압박 측 <strong>뼈 흡수</strong>·인장 측 <strong>뼈 형성</strong>.</p>' ),
		array( '얼라이너 파워칩', 'ortho', '얼라이너 사이에 걸어 힘 증대', '<p>Power Chip. 클리어얼라이너용 <strong>고무링</strong>. 어태치먼트에 걸어 힘 강화.</p>' ),
		array( '얼라이너 IPR 순서', 'ortho', '단계별 치아 사이 삭제 계획', '<p>얼라이너 시뮬레이션에 따라 <strong>단계별 IPR</strong> 시행.</p>' ),
		array( '언더라이드', 'ortho', '작은 어금니 결손 · 유치 잔존', '<p>Retained Primary Tooth. 영구치 결손으로 <strong>유치 오래 유지</strong>.</p>' ),
		array( '트랜스팔라탈 아치', 'ortho', 'TPA · 상악 어금니 연결 와이어', '<p>Transpalatal Arch. 좌우 <strong>상악 어금니 연결</strong>. 회전·확장 예방.</p>' ),
		array( '립 벤더', 'ortho', '입술 훈련·근기능 개조 장치', '<p>Lip Bumper. 하악 <strong>공간 확보·입술 근육 조절</strong>.</p>' ),
		array( '보톡스 사각턱', 'ortho', '교근 축소로 얼굴 슬림화', '<p>Masseter Botox. <strong>사각턱</strong> 원인 교근 축소. 3~6개월 효과.</p>' ),

		/* ==================== 보존·신경치료 확장 (60+) ==================== */
		array( 'Class I 와동', 'preserve', 'Blackfamily 분류 · 씹는 면 우식', '<p>Class I Cavity. <strong>어금니 씹는 면</strong> 홈 우식.</p>' ),
		array( 'Class II 와동', 'preserve', '어금니 인접면 우식', '<p>Class II. 어금니 <strong>인접면 우식</strong>. 인레이·크라운 필요.</p>' ),
		array( 'Class III 와동', 'preserve', '앞니 인접면 우식 (절단연 무관)', '<p>Class III. 앞니 <strong>사이 우식</strong>. 심미 레진 충전.</p>' ),
		array( 'Class IV 와동', 'preserve', '앞니 인접면 + 절단연 포함', '<p>Class IV. 앞니 <strong>사이 + 절단연</strong>. 대형 레진·라미네이트.</p>' ),
		array( 'Class V 와동', 'preserve', '치경부 우식', '<p>Class V. 잇몸 근처 <strong>치경부 우식</strong>. 시린 증상 동반.</p>' ),
		array( 'Class VI 와동', 'preserve', '교두정 우식', '<p>Class VI. <strong>어금니 교두 끝</strong>의 특이 우식.</p>' ),
		array( '우식 진행 E1', 'preserve', '법랑질 외측 1/2', '<p>E1. 법랑질 <strong>외측 1/2 이내</strong>. 보통 관찰·불소.</p>' ),
		array( '우식 진행 E2', 'preserve', '법랑질 내측 1/2 · DEJ 근접', '<p>E2. 법랑질 <strong>내측 1/2</strong>. 재광화 or 최소 삭제.</p>' ),
		array( '우식 진행 D1', 'preserve', '상아질 외측 1/3', '<p>D1. 상아질 <strong>외측 1/3</strong>. 레진 충전 대상.</p>' ),
		array( '우식 진행 D2', 'preserve', '상아질 중간 1/3', '<p>D2. 상아질 <strong>중간 1/3</strong>. 확실한 충전 필요.</p>' ),
		array( '우식 진행 D3', 'preserve', '상아질 내측 1/3 · 치수 근접', '<p>D3. 상아질 <strong>내측 1/3</strong>. 신경 근접·간접 복조 고려.</p>' ),
		array( '캐비티 프렙', 'preserve', '충치 부위 삭제·형태 부여', '<p>Cavity Preparation. 우식 <strong>제거·형태·유지력 부여</strong>.</p>' ),
		array( '캐비티 라이너', 'preserve', '깊은 와동 신경 보호 라이너', '<p>Cavity Liner. 수산화칼슘·GIC로 <strong>신경 자극 방지</strong>.</p>' ),
		array( '광경화 시간', 'preserve', 'LED 20초 · 할로겐 40초', '<p>Light Cure Time. LED <strong>20초 이내</strong> 완전 경화. 층별 2mm 이하.</p>' ),
		array( '레진 층별 쌓기', 'preserve', '2mm 이하로 나눠 광경화', '<p>Incremental Layering. 수축 최소화·완전 경화를 위해 <strong>2mm 층별</strong>.</p>' ),
		array( '레진 폴리싱', 'preserve', '레진 마무리·광택', '<p>Polishing. 다이아몬드·<strong>실리콘 폴리셔</strong>·페이스트로 광택.</p>' ),
		array( '다이아몬드 버', 'preserve', '경조직 삭제용 회전 도구', '<p>Diamond Bur. <strong>법랑질·세라믹</strong> 삭제에 사용. 다양한 형태.</p>' ),
		array( '카바이드 버', 'preserve', '금속·상아질 삭제용', '<p>Carbide Bur. <strong>상아질·금속</strong> 삭제. 정교한 절삭.</p>' ),
		array( '캐비티 소독', 'preserve', '레진 충전 전 세균 제거', '<p>Cavity Disinfection. <strong>클로르헥시딘</strong> 등으로 세균 감소.</p>' ),
		array( '매트릭스 밴드', 'preserve', '인접면 레진 형태 부여용', '<p>Matrix Band. <strong>인접면 벽</strong>을 형성해 정확한 형태 완성.</p>' ),
		array( '섹셔널 매트릭스', 'preserve', '섹션별 정밀 매트릭스', '<p>Sectional Matrix. Class II 레진에 <strong>정밀한 접촉점</strong> 만들기.</p>' ),
		array( '웨지', 'preserve', '매트릭스 밴드 고정용 삼각 쐐기', '<p>Wedge. 나무·플라스틱. <strong>인접면 밀착·잇몸 보호</strong>.</p>' ),
		array( 'NaOCl', 'preserve', '차아염소산나트륨 · 신경관 세척 표준', '<p>Sodium Hypochlorite. <strong>2.5~5.25% 농도</strong>. 세균·조직 용해.</p>' ),
		array( 'EDTA', 'preserve', '스미어층 제거 세척제', '<p>Ethylenediaminetetraacetic Acid. 17% 사용. <strong>미네랄 킬레이션·상아질 세척</strong>.</p>' ),
		array( 'CHX (클로르헥시딘)', 'preserve', '항균성 세척액', '<p>Chlorhexidine. 2% <strong>지속적 항균 효과</strong>. NaOCl 후 최종 세척.</p>' ),
		array( 'MTAD', 'preserve', 'Doxycycline 기반 최종 세척제', '<p>Mixture of Tetracycline, Acid, Detergent. <strong>스미어층 완전 제거</strong>.</p>' ),
		array( 'Step-back 기법', 'preserve', '아피컬 시작 · 크라운으로 확대', '<p>전통적 근관 성형법. <strong>아피컬부터 시작</strong>해 크라운쪽으로 확대.</p>' ),
		array( 'Crown-down 기법', 'preserve', '크라운부터 시작해 아피컬로', '<p>현대적 근관 성형법. <strong>크라운부터 시작</strong>·NiTi 회전 파일.</p>' ),
		array( 'Warm Vertical', 'preserve', '따뜻한 거타퍼차 수직 압박', '<p>Warm Vertical Condensation. <strong>따뜻한 거타퍼차</strong>로 근관을 완전 밀봉.</p>' ),
		array( 'Cold Lateral', 'preserve', '차가운 거타퍼차 측면 압박', '<p>Cold Lateral Condensation. <strong>차가운 거타퍼차</strong>·전통적 방법.</p>' ),
		array( 'Continuous Wave', 'preserve', '연속파 압박법', '<p>Continuous Wave. <strong>Warm vertical 변형</strong>. 신속·안정적.</p>' ),
		array( '씰러', 'preserve', '거타퍼차와 근관 벽 사이 밀봉재', '<p>Sealer. AH Plus·BioRoot RCS 등. <strong>근관 벽과 거타퍼차 밀봉</strong>.</p>' ),
		array( '바이오세라믹 씰러', 'preserve', '생체친화적 신세대 씰러', '<p>Bioceramic Sealer. BC Sealer·<strong>생체친화·재광화</strong> 유도.</p>' ),
		array( '작업 길이', 'preserve', 'WL · 신경관 세척·충전 정확 길이', '<p>Working Length. 어피컬 로케이터·X-ray로 결정. <strong>근단공에서 0.5~1mm 짧게</strong>.</p>' ),
		array( 'CBCT 신경치료', 'preserve', '3D CT로 신경관 분지·구조 확인', '<p>CBCT Endo. <strong>숨은 근관·분지·곡률</strong>을 3D로 확인. 재근관치료 필수.</p>' ),
		array( '마이크로 미러', 'preserve', '치과용 마이크로스코프 반사경', '<p>근관 내부·<strong>구석 시야 확보</strong>. 파일 파절 확인에 필수.</p>' ),
		array( '초음파 팁', 'preserve', '근관 세척·석회화 제거 초음파', '<p>Ultrasonic Tip. 초음파로 <strong>석회화·잔여물 제거</strong>. 근관 확대 보조.</p>' ),
		array( '재광화 촉진제', 'preserve', 'CPP-ACP · 재광화 지원 페이스트', '<p>Recaldent·MI Paste. <strong>칼슘·인 공급</strong>으로 재광화 촉진.</p>' ),
		array( 'MI Paste', 'preserve', 'GC사의 재광화 페이스트', '<p>MI Paste (Recaldent). 초기 우식·시린 증상·<strong>미백 후 회복</strong>에 사용.</p>' ),
		array( 'CPP-ACP', 'preserve', '카세인 인산펩티드 무정형 칼슘 인산', '<p>Casein Phosphopeptide-Amorphous Calcium Phosphate. <strong>재광화 촉진</strong> 성분.</p>' ),
		array( '치관 파절', 'preserve', '치아 관 부분이 부러진 상태', '<p>Crown Fracture. 법랑질·상아질·치수 노출 여부에 따라 <strong>치료 다름</strong>.</p>' ),
		array( '치근 파절', 'preserve', '치근이 부러진 상태 · 대부분 발치', '<p>Root Fracture. <strong>대부분 발치</strong>. 극히 일부만 재접합 가능.</p>' ),
		array( '수직 치근 파절', 'preserve', 'VRF · 치근이 세로로 갈라짐', '<p>Vertical Root Fracture. <strong>발치 원칙</strong>. 신경치료 후 오래된 치아 흔함.</p>' ),
		array( '수평 치근 파절', 'preserve', '치근이 가로로 부러짐', '<p>Horizontal Root Fracture. <strong>스플린트·경과 관찰</strong>. 예후 양호.</p>' ),
		array( '외상성 치아 파절', 'preserve', '넘어짐·충돌로 인한 파절', '<p>Traumatic Fracture. <strong>즉시 응급 처치</strong>·파편 보관·1시간 내 재부착.</p>' ),
		array( '완전 탈구', 'preserve', '치아가 완전히 빠진 상태', '<p>Avulsion. <strong>1시간 내 재식술</strong>이 예후 좌우. 우유·생리식염수 보관.</p>' ),
		array( '부분 탈구', 'preserve', '치아가 흔들리거나 이동한 상태', '<p>Luxation. 정출·함입·측방 탈구. <strong>스플린트로 고정</strong>.</p>' ),
		array( '진탕', 'preserve', '외상 후 치아 위치 정상 · 통증만', '<p>Concussion. 치아 <strong>위치 정상, 두드림 통증</strong>. 경과 관찰.</p>' ),
		array( '아탈구', 'preserve', '외상 후 치아가 흔들림', '<p>Subluxation. <strong>흔들리지만 이동 X</strong>. 부드러운 음식·경과 관찰.</p>' ),
		array( '분리된 치관·치근', 'preserve', '치관과 치근이 분리된 상태', '<p>Crown-Root Fracture. <strong>파절 위치·깊이별</strong> 치료.</p>' ),
		array( '수복 재료 종류', 'preserve', '레진·GIC·아말감·세라믹·금', '<p>레진·GIC(글래스 아이오노머)·아말감·세라믹·금. <strong>부위·크기·비용</strong>에 따라 선택.</p>' ),
		array( '레진 색상', 'preserve', 'A1~D4 등급의 레진 색상', '<p>Vita Shade. <strong>자연치와 매칭</strong>해 자연스러운 심미 회복.</p>' ),
		array( '레진 접착 시스템', 'preserve', 'Etch-and-rinse vs Self-etch', '<p>4세대(3단계)·<strong>5세대(1보틀)</strong>·6·7세대(Self-etch).</p>' ),
		array( '자가 부식 접착제', 'preserve', 'Self-etch · 술식 간소화', '<p>Self-etching. 부식·본딩을 <strong>한 번에</strong>. 술식 시간 단축.</p>' ),
		array( '전체 부식 시스템', 'preserve', 'Etch-and-rinse · 강한 결합력', '<p>Total-etch. <strong>인산 부식 후 본딩</strong>. 강한 결합.</p>' ),
		array( '초기 우식 관리', 'preserve', '삭제 없이 재광화 유도', '<p>Non-invasive. <strong>불소·CPP-ACP·MI Paste</strong>로 재광화. 삭제 X.</p>' ),
		array( '침습적 최소 치료', 'preserve', '최소 삭제 원칙 · Minimal Invasive Dentistry', '<p>MID. <strong>불필요한 삭제 최소화</strong>. 자연치아 최대 보존.</p>' ),
		array( '레진 마모', 'preserve', '10~15년 후 마모로 재수복 필요', '<p>Wear. 저작·이갈이로 마모. <strong>10~15년마다 재수복</strong>.</p>' ),
		array( '수복물 변연 착색', 'preserve', '레진 경계 착색', '<p>Marginal Staining. 세월과 함께 <strong>변연에 착색</strong>. 폴리싱으로 개선.</p>' ),

		/* ==================== 치주 확장 (40+) ==================== */
		array( '치주염 Stage I', 'periodontics', '초기 치주염 · 부착 소실 1~2mm', '<p>Stage I Periodontitis. <strong>초기 단계</strong>. 스케일링·SRP로 회복.</p>' ),
		array( '치주염 Stage II', 'periodontics', '중등도 · 부착 소실 3~4mm', '<p>Stage II. <strong>중등도 치주염</strong>. SRP + 유지관리.</p>' ),
		array( '치주염 Stage III', 'periodontics', '중증 · 부착 소실 5mm+', '<p>Stage III. <strong>수술적 치료</strong> 필요. 판막 수술·골이식.</p>' ),
		array( '치주염 Stage IV', 'periodontics', '초중증 · 다수 치아 상실', '<p>Stage IV. <strong>다수 치아 상실</strong>·재건 필요.</p>' ),
		array( '치주염 Grade A', 'periodontics', '진행 속도 느림', '<p>Grade A. <strong>느린 진행</strong>. 위험 요인 낮음.</p>' ),
		array( '치주염 Grade B', 'periodontics', '진행 속도 보통', '<p>Grade B. <strong>중등도 진행</strong>. 정기 관리 필수.</p>' ),
		array( '치주염 Grade C', 'periodontics', '진행 속도 빠름 · 위험 인자', '<p>Grade C. <strong>빠른 진행</strong>. 흡연·당뇨 등 위험 인자.</p>' ),
		array( '급성 치주염', 'periodontics', '갑작스런 심한 잇몸 염증', '<p>Acute Periodontitis. 통증·부기·<strong>고름</strong>. 즉시 배농·항생제.</p>' ),
		array( '만성 치주염', 'periodontics', '느린 진행성 잇몸 염증', '<p>Chronic Periodontitis. 가장 흔한 유형. <strong>서서히 진행</strong>·SRP 관리.</p>' ),
		array( '공격성 치주염', 'periodontics', '젊은 나이 급속 진행', '<p>Aggressive Periodontitis. <strong>젊은 나이·빠른 골 소실</strong>. 유전·면역 요인.</p>' ),
		array( '괴사성 치주염', 'periodontics', '괴사·강한 통증·궤양', '<p>Necrotizing Periodontitis. <strong>궤양·괴사·심한 통증</strong>. 면역저하자.</p>' ),
		array( '급성 괴사성 궤양성 치은염', 'periodontics', 'ANUG · 스트레스·흡연 원인', '<p>ANUG. <strong>궤양·발열·심한 구취</strong>. 즉시 치료.</p>' ),
		array( '치조골 파괴', 'periodontics', '치주염 진행 지표', '<p>Alveolar Bone Loss. X-ray로 확인. <strong>수평·수직 흡수</strong>.</p>' ),
		array( '수평 골 흡수', 'periodontics', '치조골이 평평하게 감소', '<p>Horizontal Bone Loss. <strong>균일한 골 흡수</strong>. 일반적 치주염 패턴.</p>' ),
		array( '수직 골 흡수', 'periodontics', '특정 치아 주변 골이 깊게 흡수', '<p>Vertical Bone Loss. <strong>3-Wall·2-Wall·1-Wall</strong> 결손. GTR 적응증.</p>' ),
		array( '치조골 크레이터', 'periodontics', '치조골에 U자형 결손', '<p>Bone Crater. 인접 치아 사이 <strong>U자형 골 흡수</strong>.</p>' ),
		array( '자가 골이식', 'periodontics', '자신의 뼈로 이식', '<p>Autograft. <strong>본인 뼈</strong>. 골형성 능력 최고, 채취 부담.</p>' ),
		array( '동종 골이식', 'periodontics', '기증자 인간 뼈', '<p>Allograft. FDBA·DFDBA. <strong>기증자 뼈 처리</strong>. 채취 없이 대량 사용.</p>' ),
		array( '합성 골이식', 'periodontics', 'HA·β-TCP 등 합성 골', '<p>Alloplast. 하이드록시아파타이트·베타-트리칼슘 인산. <strong>알레르기 X</strong>.</p>' ),
		array( '결합조직 이식', 'periodontics', 'CTG · 잇몸 두께 증대', '<p>Connective Tissue Graft. 상구개에서 채취해 <strong>잇몸 이식</strong>. 심미·기능.</p>' ),
		array( '유리치은 이식', 'periodontics', 'FGG · 부착치은 확보', '<p>Free Gingival Graft. <strong>각화 잇몸 확보</strong>. 잇몸 색·형태 변화 가능.</p>' ),
		array( '터널 테크닉', 'periodontics', '작은 절개로 잇몸 이식', '<p>Tunnel Technique. <strong>최소 절개</strong>. 잇몸 이식의 최신 방법.</p>' ),
		array( '코로날 상방 이동', 'periodontics', 'CAF · 잇몸을 위로 이동해 치근 덮음', '<p>Coronally Advanced Flap. <strong>잇몸 퇴축</strong>에 사용.</p>' ),
		array( '측방 회전 판막', 'periodontics', 'LSF · 인접 잇몸을 옆으로 이동', '<p>Laterally Positioned Flap. <strong>단일 치아 잇몸 퇴축</strong>에 사용.</p>' ),
		array( '치주 스플린트', 'periodontics', '흔들리는 치아를 인접 치아와 연결', '<p>Splinting. 치주염·외상으로 <strong>흔들리는 치아 안정</strong>.</p>' ),
		array( '치주 인덱스 PSR', 'periodontics', '간이 치주 스크리닝 인덱스', '<p>Periodontal Screening and Recording. <strong>0~4 등급</strong>의 간이 검사.</p>' ),
		array( 'CPI', 'periodontics', '지역사회 치주 인덱스', '<p>Community Periodontal Index. WHO 표준. <strong>공중보건</strong>용.</p>' ),
		array( '치은 지수', 'periodontics', '잇몸 염증 정도 측정', '<p>Gingival Index. Loe & Silness. <strong>0~3점</strong>으로 잇몸 염증 평가.</p>' ),
		array( '치석 지수', 'periodontics', '치석 축적 정도 측정', '<p>Calculus Index. 0~3점. <strong>스케일링 필요도</strong> 판단.</p>' ),
		array( '치은 부착 상실', 'periodontics', 'CAL · 치주염 진행 지표', '<p>Clinical Attachment Loss. <strong>치주염 심각도의 핵심 지표</strong>.</p>' ),
		array( '잇몸 두께 표현형', 'periodontics', '얇은 vs 두꺼운 잇몸 표현형', '<p>Thin·Thick Gingival Biotype. <strong>얇은 표현형</strong>은 퇴축 위험↑.</p>' ),
		array( '잇몸 유두', 'periodontics', '치아 사이 삼각 잇몸', '<p>Gingival Papilla. 치아 사이 <strong>삼각형 잇몸</strong>. 소실 시 블랙 트라이앵글.</p>' ),
		array( '블랙 트라이앵글', 'periodontics', '치아 사이 삼각형 검은 공간', '<p>Black Triangle. 잇몸 유두 <strong>소실 시 생기는 공간</strong>.</p>' ),
		array( '치은 함몰', 'periodontics', '잇몸이 얇거나 내려앉음', '<p>Gingival Recession. <strong>퇴축</strong>과 유사어. 치근 노출·시린 증상.</p>' ),
		array( '치주 재생 성장 인자', 'periodontics', 'EMD·rhPDGF-BB', '<p>Emdogain·<strong>Growth Factor</strong>. 치주 조직 재생 촉진.</p>' ),
		array( 'Emdogain', 'periodontics', '치주 재생 촉진 단백질', '<p>Enamel Matrix Derivative. 돼지 유래. <strong>치주 조직 재생 유도</strong>.</p>' ),
		array( '치주 유지관리 주기', 'periodontics', '3~6개월 정기 방문', '<p>SPT Interval. 위험도별 3·<strong>4·6개월</strong>. 재발 방지 필수.</p>' ),
		array( '치주 수술 후 부기', 'periodontics', '2~3일 절정 후 감소', '<p>냉찜질·항염제·베개 높임으로 완화. <strong>1주 후 대부분 해소</strong>.</p>' ),
		array( '치주 수술 봉합사 제거', 'periodontics', '7~10일 후 제거', '<p>Silk·Vicryl·Nylon. <strong>7~10일</strong>에 방문 제거.</p>' ),

		/* ==================== 심미치료 확장 (40+) ==================== */
		array( '앞니 모양 타입', 'aesthetic', 'Ovoid·Square·Tapered', '<p>얼굴 형태와 조화되는 앞니 모양. <strong>계란형·사각형·삼각형</strong>.</p>' ),
		array( '골든 비율', 'aesthetic', '앞니 폭·길이의 이상적 비율', '<p>Golden Ratio 1:1.618. 중절치·측절치·<strong>견치 폭 비율</strong>의 심미 원칙.</p>' ),
		array( '스마일 아크', 'aesthetic', '웃을 때 앞니 절단연 곡선', '<p>Smile Arc. 앞니 <strong>절단연이 아랫입술과 만드는 곡선</strong>. 아래 볼록이 이상적.</p>' ),
		array( '치아 노출 정도', 'aesthetic', '휴지위·발음·미소 시 앞니 노출', '<p>휴지위 2~4mm·<strong>미소 시 전체 노출</strong>이 젊고 심미적.</p>' ),
		array( '입술 폭', 'aesthetic', '웃을 때 미소 폭', '<p>Buccal Corridor. 웃을 때 입 <strong>양옆에 검은 공간</strong> 최소가 이상적.</p>' ),
		array( '미소 라인', 'aesthetic', '스마일 아크와 동일', '<p>Smile Line. 앞니 곡선. <strong>아랫입술 곡선과 조화</strong>.</p>' ),
		array( '스마일 유형', 'aesthetic', 'Low·Medium·High Smile Line', '<p>Low(잇몸 안 보임)·<strong>Medium(잇몸 1~2mm)</strong>·High(3mm+ = 거미스마일).</p>' ),
		array( '치아 착색 원인', 'aesthetic', '외인성·내인성 착색', '<p>외인성: <strong>커피·홍차·와인·담배</strong>. 내인성: 테트라사이클린·불소증·외상.</p>' ),
		array( '테트라사이클린 착색', 'aesthetic', '항생제 부작용 · 회색 착색', '<p>Tetracycline Staining. 임신·소아기 복용 → <strong>회색·갈색 띠</strong>. 미백 어려움.</p>' ),
		array( '불소증', 'aesthetic', '과다 불소로 인한 법랑질 얼룩', '<p>Fluorosis. 소아기 <strong>과도한 불소</strong> → 흰 반점·갈색 얼룩. 미백·라미네이트로 개선.</p>' ),
		array( '치아 마모증', 'aesthetic', '기계적 마모·산 부식·연마성', '<p>Attrition(치아 접촉)·<strong>Abrasion</strong>(외부 마모)·Erosion(산 부식).</p>' ),
		array( '치경부 마모', 'aesthetic', '잘못된 양치 · 치경부 파임', '<p>Cervical Abrasion. <strong>잘못된 양치</strong>로 잇몸 근처 파임. 심미 레진 복원.</p>' ),
		array( '치아 산부식', 'aesthetic', '산성 음식·역류로 인한 부식', '<p>Erosion. 산성 <strong>음료·역류성 식도염</strong> → 법랑질 손실.</p>' ),
		array( '앞니 형태 시뮬레이션', 'aesthetic', '왁스업·목업으로 결과 미리보기', '<p>Waxup·<strong>Mockup</strong>. 심미 치료 시작 전 결과 예측.</p>' ),
		array( 'Mockup', 'aesthetic', '치료 결과를 미리 만들어 봄', '<p>Mockup. <strong>임시 레진</strong>으로 결과 시뮬레이션. 환자 확인 후 진행.</p>' ),
		array( 'Waxup', 'aesthetic', '왁스로 결과 형태 제작', '<p>Waxup. 기공소에서 <strong>왁스로 예상 결과 제작</strong>. 라미네이트·크라운 계획.</p>' ),
		array( '치아 미백 원리', 'aesthetic', '과산화수소 → 산소 라디칼 → 색소 분해', '<p>과산화수소가 <strong>산소 라디칼로 분해</strong>·색소 분자 파괴.</p>' ),
		array( '미백 시 시린 증상', 'aesthetic', '상아세관 자극 · 일시적', '<p>미백제가 <strong>상아세관 침투</strong>. 대부분 미백 후 회복. 시린이 치약·불소 완화.</p>' ),
		array( '미백 유지 기간', 'aesthetic', '1~2년 후 재착색', '<p>Retention. <strong>1~2년</strong> 후 재착색. 유지 미백(터치업) 권장.</p>' ),
		array( '유지 미백', 'aesthetic', '미백 후 정기 유지 시술', '<p>Touch-up. 홈 트레이·<strong>연 1회 오피스 미백</strong>으로 유지.</p>' ),
		array( '치아 성형 (에스테틱 컨투어링)', 'aesthetic', '앞니 소량 삭제로 다듬음', '<p>Enameloplasty. 0.1~0.5mm <strong>법랑질 삭제</strong>. 통증 없이 즉시.</p>' ),
		array( '레진 재수정', 'aesthetic', '기존 레진을 재작업', '<p>Resin Repair. 착색·변색 시 <strong>부분 삭제·재충전</strong>.</p>' ),
		array( '심미 크라운', 'aesthetic', '앞니 심미 크라운 · 올세라믹', '<p>Aesthetic Crown. e.max·<strong>지르코니아 레이어링</strong>. 자연치와 구분 어려움.</p>' ),
		array( '심미 지대주', 'aesthetic', '앞니 임플란트 심미 지대주', '<p>Aesthetic Abutment. <strong>지르코니아·맞춤형</strong>. 잇몸 색·형태 최적화.</p>' ),
		array( '치아 프로포션', 'aesthetic', '앞니 폭·길이 비율', '<p>Tooth Proportion. 이상적 <strong>폭:길이 = 75~85%</strong>.</p>' ),
		array( '잇몸 대칭', 'aesthetic', '좌우 잇몸선 대칭 여부', '<p>Gingival Symmetry. <strong>좌우 잇몸 라인 대칭</strong>이 심미 핵심.</p>' ),
		array( '잇몸 라인 조정', 'aesthetic', '심미 잇몸 성형술', '<p>Gingivoplasty. <strong>레이저·전기수술</strong>로 잇몸 라인 정리.</p>' ),
		array( '심미 치과 원칙', 'aesthetic', '기능·심미 균형 · 자연 조화', '<p>Aesthetic Dentistry Principles. <strong>얼굴·입술·잇몸·치아 조화</strong>가 핵심.</p>' ),
		array( '풀 마우스 리해빌리테이션', 'aesthetic', '전악 종합 재건', '<p>Full Mouth Rehabilitation. 저작·심미·<strong>교합 종합 재건</strong>.</p>' ),
		array( '수직 고경 회복', 'aesthetic', '심한 마모로 잃은 높이 회복', '<p>Vertical Dimension Restoration. <strong>이갈이·심한 마모</strong>로 낮아진 교합 회복.</p>' ),
		array( '노인 심미치료', 'aesthetic', '시니어 심미 회복 · 자연스러움 우선', '<p>Senior Aesthetics. <strong>과도한 미백·큰 변화 지양</strong>·자연스러운 회복.</p>' ),
		array( '심미 임플란트', 'aesthetic', '앞니 임플란트 · 심미 최우선', '<p>Aesthetic Implant. <strong>이머전스 프로파일·잇몸 형태·크라운 색</strong>이 관건.</p>' ),

		/* ==================== 보철 확장 (50+) ==================== */
		array( 'Featheredge 마진', 'prosthetics', '가장 얇은 마진 · 잇몸선', '<p>Featheredge. <strong>가장 얇은 마진</strong>. 지대치 삭제 최소.</p>' ),
		array( 'Chamfer 마진', 'prosthetics', '경사진 마진 · 표준', '<p>Chamfer. <strong>경사형 마진</strong>. 지르코니아·PFM 크라운 표준.</p>' ),
		array( 'Shoulder 마진', 'prosthetics', '수평 마진 · 올세라믹용', '<p>Shoulder. <strong>수평 어깨형 마진</strong>. 올세라믹 크라운에 이상적.</p>' ),
		array( 'Deep Chamfer', 'prosthetics', '깊은 경사 마진', '<p>Deep Chamfer. Chamfer + Shoulder 중간. <strong>지르코니아 프리미엄</strong>에 사용.</p>' ),
		array( 'Knife-edge 마진', 'prosthetics', '매우 얇은 마진', '<p>Knife-edge. 극도로 얇음. <strong>금 크라운</strong>에 주로 사용.</p>' ),
		array( 'PVS 인상재', 'prosthetics', 'Polyvinyl Siloxane · 최고 정밀도', '<p>PVS. <strong>가장 정밀한 인상재</strong>. 크라운·라미네이트 제작 필수.</p>' ),
		array( '폴리에테르', 'prosthetics', '친수성 인상재 · Impregum', '<p>Polyether. <strong>친수성·정밀도 우수</strong>. Impregum 대표.</p>' ),
		array( '알지네이트', 'prosthetics', '저렴하고 빠른 인상재', '<p>Alginate. <strong>연구용 모형·의치 예비 인상</strong>에 사용.</p>' ),
		array( '이중 인상법', 'prosthetics', '베이스·워시 2단계', '<p>Two-step. <strong>베이스 인상 후 워시</strong>로 정밀 인상. 정확도 향상.</p>' ),
		array( '단일 인상법', 'prosthetics', '한 번에 인상', '<p>One-step. <strong>1회 인상</strong>. 시간 단축·정확도 낮음.</p>' ),
		array( '지대치 삭제량', 'prosthetics', '크라운 종류별 필요 삭제량', '<p>Reduction Amount. 지르코니아 <strong>0.5~1mm</strong>·PFM 1.5mm·라미네이트 0.3~0.5mm.</p>' ),
		array( '지대치 축소 각도', 'prosthetics', 'Taper 4~8도', '<p>Taper. 지대치 <strong>4~8도 각도</strong>가 이상적. 유지력·시적성.</p>' ),
		array( '상면 감소', 'prosthetics', '씹는 면 삭제량', '<p>Occlusal Reduction. 크라운 재료 두께 확보. <strong>1.5~2mm</strong>.</p>' ),
		array( '협면 감소', 'prosthetics', '볼 쪽 면 삭제량', '<p>Buccal Reduction. <strong>1~1.5mm</strong>. 심미성·유지력 균형.</p>' ),
		array( '커스텀 트레이', 'prosthetics', '개인 맞춤 인상 트레이', '<p>Custom Tray. 개인 <strong>구강 형태에 맞춤</strong>. 정밀 인상.</p>' ),
		array( '스톡 트레이', 'prosthetics', '표준 규격 트레이', '<p>Stock Tray. 표준 크기 <strong>기성 트레이</strong>. 예비 인상용.</p>' ),
		array( '스터디 모델', 'prosthetics', '진단·계획용 석고 모형', '<p>Study Model. <strong>진단·치료 계획</strong>에 사용하는 석고 모형.</p>' ),
		array( '작업 모델', 'prosthetics', '보철 제작용 정밀 모형', '<p>Working Model. <strong>정밀 인상 → 정밀 모형</strong> → 보철 제작.</p>' ),
		array( '경계 성형', 'prosthetics', '틀니 인상 시 근육 움직임 반영', '<p>Border Molding. 완전 틀니 인상 시 <strong>주변 근육 움직임 기록</strong>.</p>' ),
		array( '틀니 재료', 'prosthetics', 'PMMA 아크릴 · 표준', '<p>Denture Base. 대부분 <strong>PMMA 아크릴</strong>. 유연성 필요 시 발라스트 소재.</p>' ),
		array( '즉시 틀니', 'prosthetics', '발치 당일 착용 틀니', '<p>Immediate Denture. 발치 후 즉시 착용. <strong>미리 제작</strong>. 잇몸 안정 후 재조정.</p>' ),
		array( '임시 틀니', 'prosthetics', '최종 틀니 완성 전 착용', '<p>Interim Denture. 최종 <strong>틀니 완성까지 대체</strong>.</p>' ),
		array( '틀니 리라이닝', 'prosthetics', '틀니 내면을 새로 만들어 재적합', '<p>Reline. 잇몸이 <strong>흡수되어 틀니가 헐거워졌을 때</strong>. 1~2년마다 필요.</p>' ),
		array( '틀니 리페어', 'prosthetics', '깨진 틀니 수리', '<p>Denture Repair. 파절·마모된 틀니 <strong>부분 수리</strong>.</p>' ),
		array( '완전 틀니 인상', 'prosthetics', '무치악 특수 인상', '<p>Complete Denture Impression. <strong>기능적 인상·정확한 경계</strong>가 유지력 결정.</p>' ),
		array( '악간관계', 'prosthetics', '위·아래 턱의 위치 관계', '<p>Jaw Relation. 틀니·전악 재건에 필수. <strong>중심위·수직고경</strong> 결정.</p>' ),
		array( '중심위', 'prosthetics', 'CR · 하악의 최후방 위치', '<p>Centric Relation. <strong>턱관절 안정 위치</strong>. 보철 재건의 기준.</p>' ),
		array( '중심교합', 'prosthetics', 'CO · 상하 치아가 최대 접촉', '<p>Centric Occlusion. <strong>최대 교두감입 위치</strong>. 일상 저작 위치.</p>' ),
		array( '수직고경', 'prosthetics', '위·아래 턱의 세로 거리', '<p>Vertical Dimension. <strong>얼굴 하부 높이</strong>. 심한 마모·무치악에서 회복 필요.</p>' ),
		array( '휴지위 수직고경', 'prosthetics', '입 편안한 상태의 세로 거리', '<p>VDR. 편안한 상태. <strong>중심교합보다 2~4mm 크다</strong>.</p>' ),
		array( '페이스보우', 'prosthetics', '얼굴 프레임으로 교합 관계 기록', '<p>Facebow. 상악 위치를 <strong>교합기에 정확히 전달</strong>.</p>' ),
		array( '반조절성 교합기', 'prosthetics', '기본 조절 가능 교합기', '<p>Semi-adjustable. <strong>대부분 보철 제작</strong>에 사용. Whip Mix·Denar 등.</p>' ),
		array( '완전조절성 교합기', 'prosthetics', '개인별 완전 재현 교합기', '<p>Fully-adjustable. <strong>복잡한 전악 재건</strong>에 사용.</p>' ),
		array( '벤네트 각', 'prosthetics', '측방 이동 시 하악 각도', '<p>Bennett Angle. <strong>측방 저작 시 하악 각도</strong>. 교합기 설정.</p>' ),
		array( '힌지 축', 'prosthetics', '턱관절 회전축', '<p>Hinge Axis. <strong>순수 회전 개폐 시</strong>의 하악 축.</p>' ),
		array( '교두감입 위치', 'prosthetics', 'ICP · 최대 교합 위치', '<p>Intercuspal Position. 상하 치아가 <strong>최대로 감입</strong>되는 위치. = CO.</p>' ),
		array( '워킹 사이드', 'prosthetics', '측방 저작 시 씹는 쪽', '<p>Working Side. 측방 이동 시 <strong>씹는 쪽 치아</strong>가 접촉.</p>' ),
		array( '넌워킹 사이드', 'prosthetics', '측방 저작 시 반대 쪽', '<p>Non-working Side. <strong>씹지 않는 쪽</strong>. 접촉하면 방해.</p>' ),
		array( '교합 조정 종이', 'prosthetics', '얇은 색지로 접촉점 확인', '<p>Articulating Paper. <strong>얇은 색지</strong>. 씹을 때 접촉점을 표시.</p>' ),
		array( '이스트만 인공치', 'prosthetics', '틀니용 세라믹 인공치', '<p>Eastman Teeth. 세라믹 <strong>인공 치아</strong>. 강도·심미성.</p>' ),
		array( '아크릴 인공치', 'prosthetics', '틀니용 레진 인공치', '<p>Acrylic Teeth. 대부분 틀니. <strong>가벼움·저렴</strong>·마모 빠름.</p>' ),
		array( '완전 지르코니아 브릿지', 'prosthetics', '전악 지르코니아 브릿지', '<p>Full Zirconia Bridge. All-on-4의 <strong>최종 보철</strong> 옵션.</p>' ),
		array( '아크릴 브릿지', 'prosthetics', 'All-on-4 임시 브릿지', '<p>Acrylic Bridge. <strong>임시 or 저비용</strong> All-on-4. 파절 위험.</p>' ),
		array( '픽스 브릿지', 'prosthetics', '고정성 브릿지', '<p>Fixed Bridge. <strong>탈부착 불가</strong>. 크라운 브릿지의 표준.</p>' ),
		array( '가철성 브릿지', 'prosthetics', '탈부착 가능 부분 틀니 개념', '<p>Removable Bridge. <strong>부분 틀니</strong>. 클라스프 or 어태치먼트.</p>' ),
		array( '어태치먼트', 'prosthetics', '틀니·임플란트 연결 부품', '<p>Attachment. 볼·바·자성 등. <strong>정밀 유지력</strong>.</p>' ),
		array( '로케이터 어태치먼트', 'prosthetics', '오버덴처용 볼-소켓', '<p>Locator. 임플란트 오버덴처의 <strong>최신 어태치먼트</strong>. 유지력 조절.</p>' ),
		array( '바 어태치먼트', 'prosthetics', '임플란트 간 바로 연결·틀니 고정', '<p>Bar Attachment. 다수 임플란트 <strong>바로 연결</strong>·틀니 안정.</p>' ),
		array( '자성 어태치먼트', 'prosthetics', '자석으로 틀니 유지', '<p>Magnet Attachment. <strong>자석 유지력</strong>. 착탈 편리.</p>' ),
		array( '지르코니아 크라운 색', 'prosthetics', '흰색 → 착색 → 레이어링', '<p>모노리식 지르코니아·<strong>레이어링 지르코니아</strong>·풀 지르코니아 착색.</p>' ),
		array( '지르코니아 강도', 'prosthetics', '1000MPa+ · 강도 최고', '<p>Zirconia Strength. <strong>1000~1500MPa</strong>. 파절 위험 매우 낮음.</p>' ),
		array( 'e.max 강도', 'prosthetics', '400MPa · 심미성 최고', '<p>e.max Strength. <strong>400MPa</strong>. 지르코니아보다 낮지만 심미성 최고.</p>' ),

		/* ==================== 구강외과 확장 (40+) ==================== */
		array( '단순 발치 도구', 'surgery', '엘리베이터·포셉스', '<p>Elevator·<strong>Forceps</strong>. 치아 종류·위치별 다양한 형태.</p>' ),
		array( '엘리베이터', 'surgery', '치아를 탈구시키는 지렛대', '<p>Elevator. 잇몸 안으로 넣어 <strong>치아 탈구</strong>. 발치의 첫 단계.</p>' ),
		array( '포셉스', 'surgery', '치아를 잡아 뽑는 집게', '<p>Forceps. 어금니·<strong>앞니 포셉스</strong> 종류. 회전·측방 힘으로 발치.</p>' ),
		array( '치과 리무버', 'surgery', '고정된 치과 재료 제거 도구', '<p>Remover. 파절 <strong>임플란트·부러진 나사</strong> 등 제거.</p>' ),
		array( '외과적 발치 단계', 'surgery', '절개·박리·삭골·발치·봉합', '<p>절개 → 판막 박리 → 삭골 → 치아 분할·발치 → <strong>세척·봉합</strong>.</p>' ),
		array( '치조와 소파술', 'surgery', '발치 부위 염증 조직 제거', '<p>Curettage. 발치 후 <strong>염증·낭종 조직</strong> 큐렛으로 제거.</p>' ),
		array( '봉합사 실크', 'surgery', '전통 봉합사 · 제거 필요', '<p>Silk. 저렴·<strong>부드러움</strong>·감염 위험 약간. 7~10일 제거.</p>' ),
		array( '봉합사 나일론', 'surgery', '얇은 합성 봉합사', '<p>Nylon. <strong>비흡수성</strong>. 심미 부위·정밀 봉합.</p>' ),
		array( 'Vicryl 봉합사', 'surgery', '흡수성 봉합사', '<p>Vicryl. <strong>60~90일 흡수</strong>. 잇몸 심층 봉합에 사용.</p>' ),
		array( '프로렌 봉합사', 'surgery', '고급 합성 비흡수성', '<p>Prolene. <strong>미세·심미</strong>. 라미네이트·심미 수술.</p>' ),
		array( '봉합사 굵기', 'surgery', '3-0·4-0·5-0·6-0', '<p>숫자 클수록 얇음. <strong>구강 표준 3-0·4-0</strong>. 심미 5-0·6-0.</p>' ),
		array( '봉합사 제거 시기', 'surgery', '7~10일이 표준', '<p>구강 상처 <strong>7~10일</strong>. 심미 부위·심층 3~5일.</p>' ),
		array( '리도카인', 'surgery', '가장 흔한 국소마취제', '<p>Lidocaine. 1930년대 개발. <strong>2% + 에피네프린</strong> 표준.</p>' ),
		array( '아르티카인', 'surgery', '치과 전용 강력 마취제', '<p>Articaine. 4%. <strong>침투력 우수</strong>. 하치조 전달 마취 대체 가능.</p>' ),
		array( '메피바카인', 'surgery', '심혈관 환자용 · 에피 없는 마취', '<p>Mepivacaine. 3% <strong>에피네프린 없음</strong>. 심혈관·갑상선 환자.</p>' ),
		array( '부피바카인', 'surgery', '장시간 지속 마취', '<p>Bupivacaine. <strong>8~12시간 지속</strong>. 대형 수술 후 통증 조절.</p>' ),
		array( '에피네프린', 'surgery', '마취제 지속 시간 연장·지혈', '<p>Epinephrine. <strong>혈관 수축 → 마취 오래·지혈</strong>. 심장 질환 주의.</p>' ),
		array( '표면 마취', 'surgery', '주사 전 잇몸 표면 마취', '<p>Topical Anesthesia. <strong>주사바늘 통증</strong> 완화. 리도카인·벤조카인 젤.</p>' ),
		array( '침윤 마취', 'surgery', '치아 뿌리 주변 직접 마취', '<p>Infiltration. 상악·<strong>하악 앞니</strong>에 효과적.</p>' ),
		array( '하치조 신경 전달 마취', 'surgery', '하악 대구치용 광범위 마취', '<p>Inferior Alveolar Nerve Block. 하악 <strong>전체 이·잇몸·입술 마비</strong>.</p>' ),
		array( '아산화질소 진정', 'surgery', 'N₂O · 웃음가스 흡입 진정', '<p>Nitrous Oxide. <strong>공포·불안 감소</strong>. 소아·특수 환자.</p>' ),
		array( '경구 진정', 'surgery', '먹는 진정제 · 소아 흔함', '<p>Oral Sedation. Diazepam·<strong>Midazolam</strong>. 소아 치과 흔히 사용.</p>' ),
		array( '정맥 진정', 'surgery', 'IV Sedation · 깊은 이완', '<p>IV Sedation. 마취과 협진. <strong>완전 수면 아닌 깊은 이완</strong>.</p>' ),
		array( '전신마취', 'surgery', '완전 의식 상실', '<p>General Anesthesia. 대형 수술·<strong>극도 공포·중증 장애</strong>에서 사용.</p>' ),
		array( '아산화질소 안전성', 'surgery', '수십 년 사용된 안전한 진정법', '<p>매우 안전. <strong>임산부·정신질환</strong> 상대적 금기.</p>' ),
		array( '치아 분할 발치', 'surgery', '큰 치아를 나눠서 발치', '<p>Tooth Sectioning. 매복 사랑니·<strong>다근치</strong>를 나눠서 발치.</p>' ),
		array( '삭골', 'surgery', '치아 주변 뼈 삭제', '<p>Ostectomy. 매복 사랑니 등 <strong>덮은 뼈 제거</strong>.</p>' ),
		array( '판막 박리', 'surgery', '잇몸을 뼈에서 벗겨냄', '<p>Flap Elevation. 외과적 발치·<strong>골이식·주위염 수술</strong>에서 필수.</p>' ),
		array( '전판막', 'surgery', '완전한 삼각형 절개 판막', '<p>Full-thickness Flap. <strong>완전한 잇몸 열림</strong>. 시야 확보 우수.</p>' ),
		array( '부분판막', 'surgery', '결합조직 이식용 판막', '<p>Split-thickness Flap. <strong>결합조직만 벗김</strong>. 골막 유지.</p>' ),
		array( '봉합 방법', 'surgery', '단순·8자·연속·매트리스', '<p>Simple·Figure-8·Continuous·<strong>Horizontal/Vertical Mattress</strong>.</p>' ),
		array( '치성 낭종 종류', 'surgery', '방사성·잔유·발육성', '<p>Radicular·<strong>Residual·Dentigerous·Odontogenic Keratocyst</strong>.</p>' ),
		array( '치근단 낭종', 'surgery', '치근 끝 만성 염증성 낭종', '<p>Radicular Cyst. 신경치료 실패·<strong>만성 감염</strong>이 원인.</p>' ),
		array( '발치낭', 'surgery', '매복치 관련 발육성 낭종', '<p>Dentigerous Cyst. <strong>매복 사랑니·과잉치</strong> 주변에 흔함.</p>' ),
		array( '각화 낭종', 'surgery', 'OKC · 재발률 높은 낭종', '<p>Odontogenic Keratocyst. <strong>재발률 30~40%</strong>. 완전 절제 필수.</p>' ),
		array( '치성 종양', 'surgery', '치아 유래 양성 종양', '<p>Odontogenic Tumor. Ameloblastoma 등. <strong>수술 절제</strong>.</p>' ),
		array( 'Ameloblastoma', 'surgery', '침습적 양성 종양 · 재발 흔함', '<p>가장 흔한 치성 종양. <strong>공격적</strong>·광범위 절제 필요.</p>' ),
		array( '구강 편평 세포암', 'surgery', '가장 흔한 구강암', '<p>Oral Squamous Cell Carcinoma. 90%+ 구강암. <strong>흡연·음주</strong>가 주 원인.</p>' ),
		array( '구강암 병기', 'surgery', 'TNM 병기 시스템', '<p>Tumor·Node·Metastasis. <strong>0~IV 기</strong>. 조기 발견이 생존율 결정.</p>' ),

		/* ==================== 턱관절 확장 (30+) ==================== */
		array( '측두하악관절', 'tmj', '위·아래 턱 사이 관절 · 정식 명칭', '<p>Temporomandibular Joint. <strong>양쪽 귀 앞</strong>의 관절.</p>' ),
		array( '관절 원판 전방 변위', 'tmj', '디스크가 앞으로 밀린 상태', '<p>Anterior Disc Displacement. <strong>딱딱 소리</strong>·개구제한 원인.</p>' ),
		array( '가역성 vs 비가역성 원판 변위', 'tmj', '자연 복귀 vs 복귀 불가', '<p>With Reduction(가역)·<strong>Without Reduction</strong>(비가역).</p>' ),
		array( '개구제한 원인', 'tmj', '디스크·근육·관절 유착 등', '<p>디스크 변위·<strong>근막통증·유착·트리스무스</strong>.</p>' ),
		array( '트리스무스', 'tmj', '입 벌림 제한 · 개구제한 통칭', '<p>Trismus. <strong>입이 잘 안 벌어짐</strong>. 다양한 원인.</p>' ),
		array( '턱관절 소리 종류', 'tmj', '클릭·크레피터스', '<p>Click(딸깍)·<strong>Crepitus(사각사각)</strong>. 크레피터스는 관절 마모.</p>' ),
		array( 'TMJ MRI', 'tmj', '연조직·디스크 정밀 진단', '<p>MRI. <strong>디스크 위치·상태</strong>를 가장 정확히 진단.</p>' ),
		array( 'TMJ CBCT', 'tmj', '관절 골 구조 진단', '<p>CBCT. <strong>관절 골 형태·마모</strong> 진단.</p>' ),
		array( '관절강 세척', 'tmj', 'Arthrocentesis · 관절 안 세척', '<p>Arthrocentesis. <strong>관절 안 염증 물질 세척</strong>. 최소 침습.</p>' ),
		array( '관절경', 'tmj', 'Arthroscopy · 관절 안 내시경', '<p>Arthroscopy. <strong>관절 안 직접 관찰·수술</strong>. 유착 해소.</p>' ),
		array( '개방 관절 수술', 'tmj', 'Open Joint Surgery · 최후의 수단', '<p>Open Joint. <strong>디스크 재위치·제거·관절 대체</strong>. 극히 드물게.</p>' ),
		array( '스플린트 초기 착용', 'tmj', '2주 밤·낮 · 이후 밤만', '<p>초기 <strong>2주 밤·낮 착용</strong>·이후 야간만. 3~6개월 사용.</p>' ),
		array( '전방재위치 스플린트', 'tmj', '디스크 재위치 유도 장치', '<p>Anterior Repositioning Splint. <strong>하악을 앞으로</strong> 이동 → 디스크 정상 위치.</p>' ),
		array( 'NTI 스플린트', 'tmj', '앞니만 덮는 소형 스플린트', '<p>NTI-tss. <strong>앞니만 덮음</strong>. 편두통·이갈이에 효과.</p>' ),
		array( '항염제 (TMJ)', 'tmj', 'NSAIDs · 통증·염증 완화', '<p>NSAIDs. Ibuprofen·<strong>Naproxen</strong>. TMJ 초기 통증 조절.</p>' ),
		array( '근육 이완제', 'tmj', 'TMJ 근육 긴장 완화', '<p>Muscle Relaxant. <strong>Cyclobenzaprine</strong> 등. 저작근 이완.</p>' ),
		array( 'TMJ 물리치료', 'tmj', '스트레칭·마사지·초음파', '<p>Physical Therapy. <strong>턱관절·저작근 스트레칭</strong>·심부 마사지.</p>' ),
		array( 'TMJ 자가 관리', 'tmj', '부드러운 음식·이악물기 자제', '<p>Self-care. <strong>딱딱한 음식·껌 자제</strong>·이악물기 인식·바른 자세.</p>' ),
		array( '측두근', 'tmj', '관자놀이의 저작근', '<p>Temporalis. <strong>관자놀이</strong> 부챗살 모양. 하악 거상.</p>' ),
		array( '교근', 'tmj', '가장 강한 저작근 · 사각턱', '<p>Masseter. 가장 <strong>강력한 저작근</strong>. 사각턱 원인. 보톡스 대상.</p>' ),
		array( '내측 익돌근', 'tmj', '턱 안쪽 저작근', '<p>Medial Pterygoid. 하악 <strong>안쪽 저작근</strong>. 측방 운동.</p>' ),
		array( '외측 익돌근', 'tmj', '턱관절 원판 조절 근육', '<p>Lateral Pterygoid. <strong>관절 원판 조절</strong>. 하악 전방 이동.</p>' ),
		array( 'TMJ 두통', 'tmj', '턱관절 원인 만성 두통', '<p>TMJ Headache. 측두근·<strong>편두통과 감별</strong> 필요.</p>' ),
		array( '이명과 TMJ', 'tmj', 'TMJ 문제로 이명 발생 가능', '<p>Tinnitus. TMJ 근육 <strong>긴장이 청각에 영향</strong>. 이비인후과 감별.</p>' ),
		array( '어지러움과 TMJ', 'tmj', 'TMJ 근육 긴장이 균형 감각 영향', '<p>Vertigo. 드물지만 TMJ 원인 <strong>어지러움</strong>. 다과 진단.</p>' ),
		array( '이갈이 원인', 'tmj', '스트레스·부정교합·수면장애', '<p>Bruxism Causes. <strong>스트레스·수면 무호흡·부정교합·유전</strong>.</p>' ),
		array( '이갈이 치아 마모', 'tmj', '앞니·어금니 절단연 편평화', '<p>Attrition. <strong>절단연 마모·씹는 면 편평화</strong>. 심하면 치수 노출.</p>' ),
		array( '이갈이 진단', 'tmj', '마모·통증·수면 파트너 관찰', '<p>진단: <strong>치아 마모·아침 턱 통증·수면 파트너 관찰</strong>·수면 검사.</p>' ),
		array( 'TMJ 관절 마모', 'tmj', '만성 이갈이·과부하로 관절 파괴', '<p>Osteoarthritis. 관절 골 마모. <strong>크레피터스·통증</strong>.</p>' ),
		array( 'TMJ 강직', 'tmj', '관절 유착으로 개구 불가', '<p>Ankylosis. 관절 유착. <strong>극심한 개구 제한</strong>. 수술 필요.</p>' ),

		/* ==================== 소아치과 확장 (50+) ==================== */
		array( '유치 A', 'pediatric', '유중절치 (앞니 중앙)', '<p>Primary A. <strong>유중절치</strong>. 6~10개월 맹출.</p>' ),
		array( '유치 B', 'pediatric', '유측절치 (앞니 옆)', '<p>Primary B. <strong>유측절치</strong>. 9~13개월 맹출.</p>' ),
		array( '유치 C', 'pediatric', '유견치 (송곳니)', '<p>Primary C. <strong>유견치</strong>. 16~22개월 맹출.</p>' ),
		array( '유치 D', 'pediatric', '유제1대구치 (첫 어금니)', '<p>Primary D. <strong>유제1대구치</strong>. 13~19개월 맹출.</p>' ),
		array( '유치 E', 'pediatric', '유제2대구치 (뒤 어금니)', '<p>Primary E. <strong>유제2대구치</strong>. 25~33개월 맹출.</p>' ),
		array( '유치 맹출 순서', 'pediatric', '하악 유중절치부터 시작', '<p>보통 <strong>하악 앞니(A) → 상악 앞니 → 어금니(D) → 견치(C) → 뒤 어금니(E)</strong>.</p>' ),
		array( '영구치 맹출 순서', 'pediatric', '6세 대구치부터 시작', '<p><strong>6세 대구치 → 앞니 교체 → 소구치·견치 → 12세 대구치</strong>.</p>' ),
		array( '6세 구치', 'pediatric', '평생 사용하는 첫 영구치', '<p>First Molar. <strong>만 6세경 맹출</strong>. 유치 뒤에 새로 나옴. 실런트 필수.</p>' ),
		array( '12세 구치', 'pediatric', '두 번째 영구 대구치', '<p>Second Molar. <strong>만 12세경 맹출</strong>. 실런트 권장.</p>' ),
		array( '치아 맹출 지연', 'pediatric', '평균보다 6개월 이상 늦음', '<p>Eruption Delay. 유전·<strong>결손·과잉치·낭종</strong>. X-ray로 확인.</p>' ),
		array( '결손치', 'pediatric', '태생적으로 치아가 없음', '<p>Hypodontia·Anodontia. <strong>측절치·소구치·사랑니</strong>에 흔함.</p>' ),
		array( '거대치', 'pediatric', '평균보다 큰 치아', '<p>Macrodontia. 상악 중절치 흔함. <strong>공간 부족·심미 문제</strong>.</p>' ),
		array( '이관성 치아', 'pediatric', '뿌리가 두 개인 하나의 치아', '<p>Dens Invaginatus. 치아 내에 <strong>또 다른 치아 형태</strong>. 신경치료 복잡.</p>' ),
		array( '어린이 이갈이', 'pediatric', '유치기 이갈이 · 대부분 자연 해소', '<p>Childhood Bruxism. 대부분 <strong>영구치 교체 후 자연 해소</strong>.</p>' ),
		array( '어린이 코골이', 'pediatric', '수면 무호흡·아데노이드 관련', '<p>Pediatric Snoring. <strong>아데노이드·편도 비대</strong>가 원인. 부정교합 유발.</p>' ),
		array( '아데노이드 얼굴', 'pediatric', '입 호흡 습관으로 얼굴 변화', '<p>Adenoid Face. <strong>긴 얼굴·좁은 상악·개방교합</strong>.</p>' ),
		array( '어린이 신경치료 종류', 'pediatric', 'Pulpotomy·Pulpectomy', '<p>Pulpotomy(부분 치수 제거)·<strong>Pulpectomy(전체 치수 제거)</strong>.</p>' ),
		array( '유치 Pulpotomy', 'pediatric', '유치 치관 치수만 제거', '<p>유치의 <strong>치관부 치수 제거</strong>·잔존 치수 보존. FS·MTA 사용.</p>' ),
		array( '유치 Pulpectomy', 'pediatric', '유치 전체 치수 제거', '<p>유치 <strong>전체 신경 제거·근관 충전</strong>. ZOE·CaOH₂ 페이스트.</p>' ),
		array( 'FS (Ferric Sulfate)', 'pediatric', 'Pulpotomy용 지혈제', '<p>Ferric Sulfate. 유치 <strong>Pulpotomy 표준 재료</strong>.</p>' ),
		array( 'Formocresol', 'pediatric', '전통 Pulpotomy 재료 (사용 감소)', '<p>Formocresol. <strong>발암성 논란</strong>으로 사용 감소. FS·MTA로 대체.</p>' ),
		array( 'MTA Pulpotomy', 'pediatric', 'MTA를 이용한 최신 Pulpotomy', '<p>MTA. 생체친화·<strong>재광화 유도</strong>. 최신 선호 재료.</p>' ),
		array( '스테인리스 스틸 크라운', 'pediatric', 'SSC · 유치 어금니 표준', '<p>Stainless Steel Crown. <strong>영구치 교체까지 유지</strong>. 저렴·강도 우수.</p>' ),
		array( '지르코니아 어린이 크라운', 'pediatric', 'SSC 대안 · 심미 크라운', '<p>Zirconia Pediatric Crown. <strong>치아색 심미</strong>. SSC보다 비쌈.</p>' ),
		array( '이차 우식 (유치)', 'pediatric', '유치 충전 주변 재발 우식', '<p>Secondary Caries. 유치는 <strong>진행이 빨라 조기 발견 필수</strong>.</p>' ),
		array( '어린이 치아 외상', 'pediatric', '넘어짐·충돌로 유치·영구치 손상', '<p>Dental Trauma. <strong>즉시 응급 처치</strong>. 유치는 재식술 안 함.</p>' ),
		array( '유치 완전 탈구', 'pediatric', '유치는 재식술 안 함', '<p>Primary Tooth Avulsion. 유치는 <strong>영구치 배아 손상 우려로 재식 X</strong>.</p>' ),
		array( '영구치 완전 탈구', 'pediatric', '1시간 내 재식 필수', '<p>Permanent Tooth Avulsion. <strong>우유·생리식염수 보관 → 1시간 내 재식</strong>.</p>' ),
		array( '어린이 진정', 'pediatric', 'N₂O·경구 진정 표준', '<p>Pediatric Sedation. <strong>아산화질소·경구 진정제</strong>. 심한 공포 시 IV.</p>' ),
		array( 'Tell-Show-Do', 'pediatric', '설명 → 시연 → 시행', '<p>어린이 행동 조절 기법. <strong>설명 → 시연 → 시행</strong>으로 공포 감소.</p>' ),
		array( '긍정 강화', 'pediatric', '칭찬·보상으로 행동 유도', '<p>Positive Reinforcement. 잘한 행동에 <strong>칭찬·스티커</strong>.</p>' ),
		array( '분산 기법', 'pediatric', '주의 전환으로 공포 감소', '<p>Distraction. 영상·<strong>이야기</strong>로 주의 전환. 시술 시간 단축 효과.</p>' ),
		array( '유치 발치', 'pediatric', '영구치 교체 지연·감염 시 발치', '<p>Primary Tooth Extraction. <strong>영구치 나올 준비</strong> 되면 유치 발치.</p>' ),
		array( '공간 유지 장치 종류', 'pediatric', '고정식 vs 가철식', '<p>Band and Loop·Distal Shoe·<strong>Lingual Arch</strong>·가철식.</p>' ),
		array( 'Band and Loop', 'pediatric', '단일 치아 결손용 공간유지', '<p>Band and Loop. <strong>단일 유치 조기 상실</strong>에 사용.</p>' ),
		array( 'Lingual Arch', 'pediatric', '하악 다수 치아 공간 유지', '<p>Lingual Arch. 하악 <strong>양측 대구치 연결</strong>. 공간 유지.</p>' ),
		array( 'Distal Shoe', 'pediatric', '유치 조기 상실 시 사용', '<p>Distal Shoe. 유치 E 조기 상실 시 <strong>영구치 6세 대구치 유도</strong>.</p>' ),
		array( '어린이 습관 교정 장치', 'pediatric', 'Habit Breaker · Hay Rake', '<p>Habit Appliance. <strong>손가락 빨기·혀 내밀기</strong> 교정.</p>' ),
		array( 'Hay Rake', 'pediatric', '갈퀴형 습관 교정 장치', '<p>Hay Rake. <strong>혀 내밀기·손가락 빨기</strong> 방지 갈퀴형 장치.</p>' ),
		array( '팜 크러스트', 'pediatric', '손가락 위에 압력 감지 장치', '<p>Palm Crib. <strong>손가락 빨기</strong> 인식·중단 유도.</p>' ),
		array( '어린이 교정 장치', 'pediatric', 'Nance·Herbst·Twin block', '<p>Nance(공간유지)·<strong>Herbst</strong>(Class II)·Twin Block(기능성).</p>' ),
		array( 'Twin Block', 'pediatric', 'Class II 성장기 교정', '<p>Twin Block. 상하 <strong>이중 블록</strong>으로 하악 전방 유도.</p>' ),
		array( 'Herbst', 'pediatric', '고정식 Class II 교정', '<p>Herbst. <strong>고정식 하악 전방 유도</strong>. 청소년 Class II.</p>' ),
		array( 'ELF (Early Lower Fixed)', 'pediatric', '조기 하악 교정', '<p>혼합치열기 <strong>하악 조기 교정</strong>.</p>' ),
		array( '어린이 예방적 치과', 'pediatric', '실런트·불소·정기 검진', '<p>어린이는 <strong>예방이 치료보다 훨씬 효과적</strong>. 정기 관리 필수.</p>' ),
		array( '어린이 우식 예방', 'pediatric', '식이 · 양치 · 실런트 · 불소', '<p>단순 <strong>식이 조절</strong>·정기 양치·실런트·불소·정기 검진.</p>' ),
		array( '어린이 정기 검진 주기', 'pediatric', '6개월 표준 · 위험군 3개월', '<p>일반 <strong>6개월</strong>. 우식 위험 높으면 <strong>3~4개월</strong>.</p>' ),
		array( '유치 우식률', 'pediatric', '한국 유치 우식률 60%+', '<p>한국 <strong>5세 유치 우식률 60%+</strong>. 예방 교육 중요.</p>' ),
		array( '어린이 방사선 안전', 'pediatric', '납 앞치마·최소 노출', '<p>Pediatric X-ray Safety. <strong>납 앞치마·갑상선 보호대 필수</strong>. 디지털 X-ray.</p>' ),

		/* ==================== 예방·검진 확장 (40+) ==================== */
		array( '정기 검진 항목', 'prevention', '시진·촉진·X-ray·구강암 검진', '<p>Comprehensive Exam. <strong>시진·촉진·프로빙·X-ray·구강암 스크리닝</strong>.</p>' ),
		array( '치과 검진 주기', 'prevention', '6개월 표준 · 고위험군 3개월', '<p>일반 6개월. <strong>치주염·임플란트·당뇨·흡연</strong>은 3~4개월.</p>' ),
		array( '스케일링 프로토콜', 'prevention', '초음파 → 큐렛 → 폴리싱', '<p>초음파 스케일러 → 손 큐렛 → <strong>폴리싱·불소도포</strong>.</p>' ),
		array( '스케일링 시간', 'prevention', '평균 30~40분', '<p>Scaling Duration. <strong>30~40분</strong>. 치석 많으면 60분 이상.</p>' ),
		array( '스케일링 후 시린 증상', 'prevention', '1~3일 지속 후 회복', '<p>Post-scaling Sensitivity. <strong>1~3일</strong> 시린이 치약·불소도포로 완화.</p>' ),
		array( '에어폴리싱', 'prevention', '미세 분말·에어플로우 통칭', '<p>Air Polishing. <strong>미세 분말+물</strong>로 색소·바이오필름 제거.</p>' ),
		array( '글리신 분말', 'prevention', '임플란트 안전 에어플로우 분말', '<p>Glycine Powder. <strong>임플란트 표면 손상 없이</strong> 사용 가능.</p>' ),
		array( '에리스리톨 분말', 'prevention', '가장 부드러운 에어플로우 분말', '<p>Erythritol. <strong>임플란트·치주염 부위</strong> 안전. 최신.</p>' ),
		array( '중탄산나트륨 분말', 'prevention', '전통 에어플로우 분말', '<p>Sodium Bicarbonate. <strong>전통 분말</strong>. 자연치아만 사용.</p>' ),
		array( '불소 젤', 'prevention', '트레이로 도포하는 고농도 불소', '<p>APF·Neutral NaF. <strong>트레이로 4분간</strong> 도포.</p>' ),
		array( '불소 폼', 'prevention', '거품 형태 불소 도포', '<p>Fluoride Foam. <strong>거품</strong>이라 소량 사용. 소아에 편리.</p>' ),
		array( '불소 바니시 도포법', 'prevention', '치아 표면 직접 도포', '<p>Varnish. <strong>도포 후 4시간 음식·양치 금지</strong>.</p>' ),
		array( '실런트 도포 절차', 'prevention', '세척 → 부식 → 세척 → 도포 → 광경화', '<p>Sealant Procedure. 세척·<strong>부식·본딩·광경화</strong>. 10~15분.</p>' ),
		array( '실런트 성공률', 'prevention', '완전 유지 시 5년 90%+', '<p>Retention. 5년 <strong>90%+ 성공률</strong>. 정기 확인·재도포.</p>' ),
		array( '어린이 실런트 시기', 'prevention', '6세 구치·12세 구치 맹출 직후', '<p>6세 대구치·12세 대구치가 <strong>완전 맹출 직후</strong> 실런트.</p>' ),
		array( '스포츠 마우스가드', 'prevention', '스포츠 활동 시 치아 보호', '<p>Sports Mouth Guard. <strong>맞춤·기성</strong>. 격투기·축구·농구.</p>' ),
		array( '치실 사용법', 'prevention', 'C자로 감싸며 아래위', '<p>Flossing Technique. <strong>C자로 치아 감싸며 위아래</strong> 움직임.</p>' ),
		array( '치실 종류', 'prevention', '왁스·논왁스·플로스 스틱', '<p>Waxed·Unwaxed·<strong>Floss Stick</strong>. 편리성별 선택.</p>' ),
		array( '치간 칫솔 크기', 'prevention', '치아 사이 공간에 맞게 선택', '<p>Interdental Brush Size. <strong>ISO 0~7</strong>. 치아 사이 폭에 맞춤.</p>' ),
		array( '워터플로서 사용법', 'prevention', '치아 사이·잇몸 라인 각도', '<p>Water Flosser Use. <strong>90도 각도</strong>·치아 사이 1~2초.</p>' ),
		array( '전동 칫솔 종류', 'prevention', '초음파·회전·진동', '<p>Sonicare(초음파)·<strong>Oral-B(회전 진동)</strong>. 개인 취향.</p>' ),
		array( '수동 vs 전동 칫솔', 'prevention', '올바른 사용법이 더 중요', '<p>Manual vs Electric. <strong>올바른 사용법이 도구보다 중요</strong>. 전동 20%+ 효율.</p>' ),
		array( '치약 성분 불소 농도', 'prevention', '성인 1000~1500ppm·소아 500ppm', '<p>불소 <strong>ppm(백만분율)</strong>. 성인 1000~1500·<strong>3세 이상 소아 500~1000</strong>·3세 미만 200.</p>' ),
		array( '치약 성분 계면활성제', 'prevention', 'SLS 등 · 거품 생성', '<p>Sodium Lauryl Sulfate. <strong>거품 생성</strong>. 구내염 유발 가능.</p>' ),
		array( '치약 성분 항균제', 'prevention', '트리클로산·클로르헥시딘', '<p>Triclosan(사용 감소)·<strong>클로르헥시딘</strong>. 잇몸염 예방.</p>' ),
		array( '가글 성분', 'prevention', '클로르헥시딘·불소·염화세틸피리디늄', '<p>Chlorhexidine(강력 항균)·<strong>NaF</strong>·CPC(온화 항균).</p>' ),
		array( '가글 사용법', 'prevention', '30초 헹구고 뱉기', '<p>Mouthwash Use. <strong>30초 이상 헹굼</strong>·삼키지 않기·30분 음식 금지.</p>' ),
		array( '설태 원인', 'prevention', '세균·음식물·구강 건조', '<p>Coated Tongue. <strong>세균·음식물·설유두 각화</strong>. 구취 주 원인.</p>' ),
		array( '올바른 양치 시간', 'prevention', '3분 이상 · 부위별 균등', '<p>3분 이상. <strong>1/4씩 45초</strong> 균등 배분. 잇몸 라인 필수.</p>' ),
		array( '양치질 순서', 'prevention', '상 → 하 · 바깥 → 안 · 씹는 면', '<p>순서 <strong>루틴화</strong>가 중요. 놓치는 부위 최소화.</p>' ),
		array( '식사 후 양치 시기', 'prevention', '식후 30분 후 권장', '<p>산성 음식 후 즉시 양치 시 <strong>법랑질 손상</strong>. 30분 후 권장.</p>' ),
		array( '자기 전 양치 필수', 'prevention', '침 분비 감소 시간 대비', '<p>수면 중 <strong>침 분비 감소</strong>·세균 활발. 자기 전 양치 필수.</p>' ),
		array( '구강 검진 주기', 'prevention', '6개월 · 위험군 3개월', '<p>일반 6개월. <strong>위험군 3~4개월</strong>. 정기 관리가 최선 예방.</p>' ),
		array( '치과 방사선 필터', 'prevention', '알루미늄 필터로 저에너지 X선 차단', '<p>Aluminum Filter. <strong>불필요한 저에너지 X선 차단</strong>. 환자 안전.</p>' ),
		array( '치과 방사선 방향', 'prevention', '반드시 필요한 부위만', '<p>ALARA. <strong>As Low As Reasonably Achievable</strong>. 최소 노출 원칙.</p>' ),
		array( 'BiteWing X-ray', 'prevention', '어금니 사이 우식 진단', '<p>Bitewing. <strong>어금니 사이 우식·치조골 상단</strong> 진단.</p>' ),
		array( 'FMX (전악 촬영)', 'prevention', '14~18장 종합 촬영', '<p>Full Mouth X-ray. 전체 치아 <strong>14~18장 종합</strong>. 5~7년 주기.</p>' ),

		/* ==================== 일반·해부·기타 확장 (70+) ==================== */
		array( 'FDI 표기법', 'general', '국제 표준 치아 번호 · 11~48', '<p>FDI. 상악 우측 1사분면부터 <strong>시계방향</strong>. 11~48 두 자리.</p>' ),
		array( 'Universal 표기법', 'general', '미국 표준 · 1~32', '<p>Universal. 상악 우측 3대구치부터 <strong>1~32번</strong>.</p>' ),
		array( 'Palmer 표기법', 'general', '영국·교정과 · 사분면 기호', '<p>Palmer. <strong>사분면 기호 + 숫자</strong>. 교정에서 흔히 사용.</p>' ),
		array( '유치 표기법', 'general', '알파벳 A~T (Universal)', '<p>Primary Notation. <strong>Universal A~T</strong>·FDI 51~85.</p>' ),
		array( '치아 5면', 'general', '근심·원심·협·설·교합', '<p>Mesial·Distal·<strong>Buccal(Labial)·Lingual(Palatal)·Occlusal(Incisal)</strong>.</p>' ),
		array( '근심', 'general', '치아의 정중선 쪽 면', '<p>Mesial. <strong>정중선 쪽</strong> 면. FDI 표기 기준.</p>' ),
		array( '원심', 'general', '치아의 정중선 반대 쪽 면', '<p>Distal. <strong>정중선 반대</strong> 쪽 면. 사랑니 방향.</p>' ),
		array( '구개면', 'general', '상악 치아의 안쪽 면', '<p>Palatal. <strong>상악 치아의 안쪽</strong> (구개 쪽).</p>' ),
		array( '순면', 'general', '앞니의 입술 쪽 면', '<p>Labial. <strong>앞니의 입술 쪽</strong> 면.</p>' ),
		array( '치관 형태', 'general', '앞니 삼각형·어금니 사각형', '<p>Crown Morphology. <strong>앞니는 절단연, 어금니는 씹는 면</strong> 위주.</p>' ),
		array( '유공 (근단공)', 'general', '치근 끝 신경관 통로', '<p>Apical Foramen. <strong>신경·혈관이 드나드는 구멍</strong>.</p>' ),
		array( '보조 근단공', 'general', '주 근단공 옆의 부속 통로', '<p>Accessory Foramen. 신경치료 시 <strong>세척 어려운 부위</strong>.</p>' ),
		array( '치수강', 'general', '치아 중심의 신경·혈관 공간', '<p>Pulp Chamber. 치관부 <strong>치수가 있는 공간</strong>.</p>' ),
		array( '근관', 'general', '치근 안의 신경관', '<p>Root Canal. <strong>치근 내 신경·혈관 통로</strong>. 신경치료 대상.</p>' ),
		array( '치조돌기', 'general', '턱뼈의 치아를 지탱하는 부분', '<p>Alveolar Process. 상악골·하악골의 <strong>치아 지지 부분</strong>.</p>' ),
		array( '피질골', 'general', '뼈의 단단한 바깥층', '<p>Cortical Bone. <strong>뼈의 겉껍질</strong>. 임플란트 초기 고정력 결정.</p>' ),
		array( '해면골', 'general', '뼈 내부 성긴 구조', '<p>Cancellous Bone. <strong>뼈 내부 스폰지 구조</strong>. 골세포·혈관 풍부.</p>' ),
		array( '골 재생', 'general', '뼈 조직의 자연 재생 능력', '<p>Bone Regeneration. <strong>골이식·성장인자·차폐막</strong>으로 유도 가능.</p>' ),
		array( '골 리모델링', 'general', '지속적 뼈 흡수·재형성', '<p>Bone Remodeling. <strong>파골세포·조골세포</strong>의 균형. 교정 이동 원리.</p>' ),
		array( '파골세포', 'general', '뼈 흡수 세포', '<p>Osteoclast. <strong>뼈를 흡수</strong>하는 세포. 리모델링에 필수.</p>' ),
		array( '조골세포', 'general', '뼈 형성 세포', '<p>Osteoblast. <strong>뼈를 형성</strong>하는 세포. 골이식 성공의 핵심.</p>' ),
		array( '골세포', 'general', '성숙 뼈세포', '<p>Osteocyte. 조골세포가 <strong>골 기질에 갇힌 상태</strong>. 뼈 유지.</p>' ),
		array( '삼차 신경', 'general', '얼굴·구강 감각 담당 뇌신경', '<p>Trigeminal Nerve (V). <strong>V1(안)·V2(상악)·V3(하악)</strong> 세 갈래.</p>' ),
		array( 'V2 상악 신경', 'general', '상악 치아·잇몸 감각', '<p>Maxillary Nerve. <strong>상악 치아·구개·뺨</strong>의 감각.</p>' ),
		array( 'V3 하악 신경', 'general', '하악 치아·혀 감각·저작근 운동', '<p>Mandibular Nerve. <strong>하악 치아·혀·저작근 운동</strong>.</p>' ),
		array( '하치조 신경', 'general', '하악 어금니·앞니·입술 감각', '<p>Inferior Alveolar Nerve. V3의 가지. <strong>하악 신경관</strong> 통과.</p>' ),
		array( '설신경', 'general', '혀 앞 2/3 감각', '<p>Lingual Nerve. V3의 가지. <strong>혀 앞부분 감각</strong>. 사랑니 발치 시 주의.</p>' ),
		array( '이신경', 'general', '하악 앞부분·아래턱 감각', '<p>Mental Nerve. 하치조 신경 종말 가지. <strong>턱·아래 입술</strong>.</p>' ),
		array( '협신경', 'general', '볼 안쪽·잇몸 감각', '<p>Buccal Nerve. V3의 가지. <strong>협면 잇몸·볼 안쪽</strong>.</p>' ),
		array( '후상치조 신경', 'general', '상악 어금니 감각', '<p>Posterior Superior Alveolar Nerve. <strong>상악 어금니</strong> 신경.</p>' ),
		array( '중상치조 신경', 'general', '상악 소구치 감각', '<p>Middle Superior Alveolar Nerve. <strong>상악 소구치</strong> 담당.</p>' ),
		array( '전상치조 신경', 'general', '상악 앞니·견치 감각', '<p>Anterior Superior Alveolar Nerve. <strong>상악 앞니·견치</strong> 담당.</p>' ),
		array( '안면 신경', 'general', '얼굴 표정 근육 운동 (VII)', '<p>Facial Nerve (VII). <strong>표정근 운동·미각 앞 2/3</strong>.</p>' ),
		array( '이하선', 'general', '가장 큰 침샘 · 귀 앞', '<p>Parotid Gland. <strong>가장 큰 침샘</strong>. 스텐센 관으로 상악 어금니 부근에 배출.</p>' ),
		array( '악하선', 'general', '두 번째로 큰 침샘 · 턱 아래', '<p>Submandibular Gland. <strong>턱 아래</strong>. 왈튼 관으로 혀 아래 배출.</p>' ),
		array( '설하선', 'general', '가장 작은 침샘 · 혀 아래', '<p>Sublingual Gland. <strong>혀 아래</strong>. 여러 작은 관으로 배출.</p>' ),
		array( '소타액선', 'general', '입안 곳곳 작은 침샘', '<p>Minor Salivary Glands. <strong>구개·볼·혀</strong> 등 곳곳. 미각·윤활.</p>' ),
		array( '침 분비량', 'general', '하루 1~1.5L 정상', '<p>Saliva Volume. 성인 <strong>하루 1~1.5L</strong>. 스트레스·약물로 감소.</p>' ),
		array( '침 pH', 'general', '정상 6.2~7.6', '<p>Salivary pH. <strong>6.2~7.6</strong>. 5.5 미만 시 법랑질 부식.</p>' ),
		array( '침 완충 능력', 'general', '산성 중화 · 재광화', '<p>Buffering Capacity. 중탄산·<strong>인산·단백질</strong> 완충. 우식 예방.</p>' ),
		array( '침 성분 아밀라아제', 'general', '탄수화물 분해 효소', '<p>Amylase. <strong>탄수화물 분해</strong>. 소화 시작.</p>' ),
		array( '침 성분 뮤신', 'general', '점성·윤활 단백질', '<p>Mucin. <strong>침의 점성·윤활</strong>. 삼킴·발음 보조.</p>' ),
		array( '침 성분 IgA', 'general', '면역 항체', '<p>Secretory IgA. <strong>구강 면역</strong>. 세균 억제.</p>' ),
		array( '침 성분 리소자임', 'general', '세균 세포벽 분해 효소', '<p>Lysozyme. <strong>세균 세포벽 분해</strong>. 항균.</p>' ),
		array( '뮤탄스균 감염', 'general', '주로 유아기 감염 · 수직 감염', '<p>어머니의 <strong>침·식기 공유</strong>로 유아기 감염. 우식 시작.</p>' ),
		array( '락토바실러스', 'general', '우식 진행에 관여', '<p>Lactobacillus. 뮤탄스균 다음 우식 진행 <strong>깊은 우식</strong>에 관여.</p>' ),
		array( '악티노마이세스', 'general', '치석·치주염 관여', '<p>Actinomyces. <strong>치석·치주염</strong> 관여 세균.</p>' ),
		array( 'Porphyromonas gingivalis', 'general', '치주염 대표 원인균', '<p>P.gingivalis. <strong>Red Complex</strong>의 대표. 치주염 진행 핵심.</p>' ),
		array( '침샘 결석', 'general', '침샘관에 결석 형성 · 타석증', '<p>Sialolith. <strong>침샘관 막힘·통증·부기</strong>. 외과적 제거.</p>' ),
		array( '침샘염', 'general', '침샘의 세균성 염증', '<p>Sialadenitis. <strong>이하선·악하선 염증</strong>. 항생제·수분·마사지.</p>' ),
		array( '유행성 이하선염', 'general', '멈프스 바이러스 감염 · 볼거리', '<p>Mumps. <strong>양쪽 이하선 부기</strong>. MMR 백신으로 예방.</p>' ),
		array( '구강 건조증 원인', 'general', '약물·질환·방사선', '<p>Xerostomia. <strong>항우울제·항히스타민제·이뇨제</strong>·쇼그렌 증후군.</p>' ),
		array( '쇼그렌 증후군', 'general', '자가면역 구강·눈 건조', '<p>Sjögren\'s Syndrome. <strong>침·눈물 감소</strong>. 자가면역 질환.</p>' ),
		array( '구강 편평태선', 'general', '자가면역 구강 점막 질환', '<p>Oral Lichen Planus. <strong>흰 줄무늬·궤양</strong>. 스테로이드 관리.</p>' ),
		array( '편평태선 원인', 'general', '자가면역·스트레스·약물', '<p>정확한 원인 미상. <strong>자가면역·스트레스·간염 관련</strong> 가설.</p>' ),
		array( '천포창', 'general', '자가면역 수포성 질환', '<p>Pemphigus. <strong>물집·궤양</strong>. 심각 질환. 면역 억제 치료.</p>' ),
		array( '유천포창', 'general', '자가면역 수포성 · 노인 흔함', '<p>Pemphigoid. 천포창보다 <strong>덜 심각</strong>. 노인 흔함.</p>' ),
		array( '베체트병', 'general', '자가면역 · 구내염 반복', '<p>Behçet\'s Disease. <strong>구내염·성기 궤양·눈 염증</strong>.</p>' ),
		array( '아프타 궤양 원인', 'general', '스트레스·비타민 부족·유전', '<p>Aphthous Ulcer. <strong>정확한 원인 미상</strong>. 스트레스·B12·철분 결핍.</p>' ),
		array( 'HSV-1', 'general', '입술 헤르페스 원인 바이러스', '<p>Herpes Simplex Virus 1. <strong>입술 물집·궤양</strong> 반복 재발.</p>' ),
		array( '구내 헤르페스', 'general', '입안 헤르페스 감염', '<p>Intraoral Herpes. 잇몸·<strong>구개·혀</strong> 물집·궤양.</p>' ),
		array( '아구창', 'general', '유아·면역저하자 곰팡이 감염', '<p>Oral Thrush. Candida albicans. <strong>흰 막·붉은 궤양</strong>.</p>' ),
		array( '구강 결핵', 'general', '드문 구강 결핵 감염', '<p>Oral Tuberculosis. <strong>매우 드묾</strong>. 결핵 환자의 폐 감염 파급.</p>' ),
		array( '치과 마취 알레르기', 'general', '마취제 알레르기 · 드묾', '<p>Anesthetic Allergy. <strong>매우 드물다</strong>. 방부제 알레르기가 더 흔함.</p>' ),
		array( '진통제 종류', 'general', 'NSAIDs·아세트아미노펜·아편계', '<p>NSAIDs(Ibuprofen)·<strong>Acetaminophen</strong>·Opioids(심한 통증).</p>' ),
		array( 'Ibuprofen', 'general', '가장 흔한 NSAIDs · 진통·항염', '<p>Ibuprofen. <strong>치과 통증 1차 선택</strong>. 400~600mg 4~6시간.</p>' ),
		array( 'Acetaminophen', 'general', '타이레놀 · 아이 안전', '<p>Acetaminophen (Tylenol). <strong>임산부·아이 안전</strong>. NSAIDs 병용 가능.</p>' ),
		array( '치과 항생제 종류', 'general', 'Amoxicillin·Clindamycin', '<p>Amoxicillin (1차)·<strong>Clindamycin (페니실린 알레르기)</strong>.</p>' ),
		array( 'Amoxicillin', 'general', '치과 항생제 1차 선택', '<p>Amoxicillin. <strong>가장 흔한 치과 항생제</strong>. 500mg 8시간마다.</p>' ),
		array( 'Clindamycin', 'general', '페니실린 알레르기 대안', '<p>Clindamycin. <strong>페니실린 알레르기</strong>·심혈관 예방 항생제.</p>' ),
		array( 'Metronidazole', 'general', '혐기성 세균 항생제', '<p>Metronidazole. <strong>치주염·급성 감염</strong>. Amoxicillin 병용.</p>' ),
		array( '치과 약물 상호작용', 'general', '와파린·MAO 억제제 주의', '<p>와파린(INR↑)·<strong>MAOI(에피네프린 위험)</strong>·비스포스포네이트(BRONJ).</p>' ),
		array( '치과 초음파 세척기', 'general', '기구 세척 표준', '<p>Ultrasonic Cleaner. <strong>초음파 진동</strong>으로 미세 오염 제거. 오토클레이브 전 단계.</p>' ),
		array( '핸드피스 소독', 'general', '오토클레이브 멸균', '<p>Handpiece Sterilization. <strong>오토클레이브 필수</strong>. 매 환자마다 교체.</p>' ),
		array( '개인 보호구 (PPE)', 'general', '마스크·장갑·보안경', '<p>Personal Protective Equipment. <strong>매 환자마다 새것</strong>. 감염 예방.</p>' ),
		array( '치과 폐수 처리', 'general', '아말감 필터·감염성 폐수', '<p>Amalgam Separator·<strong>감염성 폐수 별도 처리</strong>. 환경법 준수.</p>' ),
	);
}

/**
 * v3.35.3 · 3차 대량 확장 시드 마이그레이션.
 */
add_action( 'init', function() {
	if ( get_option( 'moondental_encyclopedia_v3353_expand' ) === 'done' ) return;
	if ( ! post_type_exists( 'md_term' ) ) return;

	$data = moondental_encyclopedia_seed_data_v3353();

	foreach ( $data as $t ) {
		list( $title, $cat, $excerpt, $body ) = $t;

		// 중복 스킵
		$existing = get_posts( array(
			'post_type'      => 'md_term',
			'title'          => $title,
			'posts_per_page' => 1,
			'post_status'    => 'any',
			'fields'         => 'ids',
			'no_found_rows'  => true,
		) );
		if ( ! empty( $existing ) ) continue;

		$post_id = wp_insert_post( array(
			'post_type'    => 'md_term',
			'post_status'  => 'publish',
			'post_title'   => $title,
			'post_excerpt' => $excerpt,
			'post_content' => $body,
			'post_name'    => sanitize_title( $title ),
		) );
		if ( $post_id && ! is_wp_error( $post_id ) ) {
			$term = get_term_by( 'slug', $cat, 'md_term_category' );
			if ( $term ) {
				wp_set_object_terms( $post_id, array( $term->term_id ), 'md_term_category' );
			}
		}
	}

	update_option( 'moondental_encyclopedia_v3353_expand', 'done' );
}, 45 );
