<?php
/**
 * Moon Dental · 치과사전 2차 확장 시드 (180+ 개 추가)
 *
 *  v3.35.2 · bdbddc.com/encyclopedia sitemap 참고 · 놓친 용어 대량 추가.
 *  중복 스킵 → 신규만 추가. wp-admin에서 이후 자유롭게 편집.
 *
 * @package moondental-child
 */

if ( ! defined( 'ABSPATH' ) ) exit;

function moondental_encyclopedia_seed_data_v3352() {
	return array(

		/* ==================== 임플란트 (추가) ==================== */
		array( '임플란트 신경 손상', 'implant', '식립 중 하치조 신경을 건드릴 위험', '<p>하악 임플란트 시 <strong>하치조 신경관</strong>을 침범하면 입술·턱 감각 마비 위험. CBCT 정밀 진단·네비게이션 가이드로 예방.</p>' ),
		array( '임플란트 재수술', 'implant', '실패·주위염 후 재식립', '<p>골유착 실패·주위염으로 임플란트 제거 후 <strong>골이식·회복 기간</strong>을 거쳐 재식립. 성공률 80% 내외.</p>' ),
		array( '임플란트 골유착 실패', 'implant', '골과 융합되지 않아 흔들리는 상태', '<p>주요 원인: 초기 감염·과부하·흡연·당뇨. <strong>3~6개월 내 흔들림 발생</strong> 시 제거·재식립 검토.</p>' ),
		array( '임플란트 상악동 침범', 'implant', '상악 어금니 부위 임플란트가 상악동을 뚫는 경우', '<p>골량 부족 시 발생 가능. <strong>상악동 거상술·짧은 임플란트</strong>로 예방. CBCT 필수.</p>' ),
		array( '무절개 임플란트', 'implant', '잇몸 절개 없이 펀치로 식립', '<p>Flapless implant. 잇몸에 <strong>펀치로 구멍만 뚫어</strong> 식립. 통증·붓기 최소, 회복 빠름. 골량이 충분해야 가능.</p>' ),
		array( '가이드 수술', 'implant', 'CBCT 데이터 기반 수술 가이드 사용', '<p>Guided Surgery. 3D CBCT로 <strong>수술 가이드(스텐트)</strong>를 미리 제작해 정확도 극대화.</p>' ),
		array( '수술 가이드', 'implant', '임플란트 위치·각도 정밀 유도 장치', '<p>Surgical Guide. 3D 프린팅으로 제작. 드릴 방향과 <strong>깊이를 제한</strong>해 실수 방지.</p>' ),
		array( '임플란트 픽스처 파절', 'implant', '픽스처가 부러지는 드문 합병증', '<p>주로 과부하·불량 위치 식립으로 발생. <strong>제거 후 재식립</strong>이 원칙. 예방: 정기 검진·이갈이 관리.</p>' ),
		array( '해외 임플란트 비교', 'implant', '국내산 vs 유럽·미국 브랜드 비교', '<p>ITI 스트라우만·노벨 바이오케어(유럽·미국) vs 오스템·메가젠(국산). 성공률 비슷, <strong>가격·A/S·부품 공급</strong>에서 차이.</p>' ),
		array( '임플란트 인상', 'implant', '식립 후 최종 보철용 본 뜨기', '<p>Implant Impression. <strong>임프레션 코핑</strong>을 픽스처에 연결 후 실리콘/디지털 인상. 정밀도가 보철 성패 결정.</p>' ),
		array( '임플란트 어버트먼트', 'implant', '픽스처와 크라운을 연결하는 부품', '<p>지대주와 동의어. 기성·맞춤·앵글드·힐링 등 다양한 종류.</p>' ),
		array( '임플란트 임시치아', 'implant', '최종 보철 완성 전 임시 크라운', '<p>즉시 하중·심미 부위에서 <strong>수술 당일 임시 크라운</strong> 장착. PMMA 소재.</p>' ),
		array( '임플란트 실패', 'implant', '골유착 실패 또는 만성 감염', '<p>초기 실패(1년 내)·후기 실패(1년 이후). 5년 실패율 5% 미만.</p>' ),
		array( '임플란트 후 관리', 'implant', '평생 관리가 임플란트 수명을 결정', '<p>양치·치실·워터픽·정기 검진·스케일링. <strong>3~6개월 정기 검진</strong>이 임플란트 주위염 예방.</p>' ),
		array( '임플란트 관리', 'implant', '임플란트 전용 위생 관리', '<p>임플란트 주위 청결이 가장 중요. <strong>일반 스케일러 대신 임플란트 전용 스케일러</strong> 사용.</p>' ),
		array( '원데이 임플란트', 'implant', '하루에 발치+식립+임시치아', '<p>Immediate loading. 발치·식립·임시 크라운을 <strong>당일 완료</strong>. 심미부·전치부에 특히 유리.</p>' ),
		array( '드라이 소켓', 'implant', '발치 후 혈전이 소실되어 뼈가 노출된 상태', '<p>Alveolar Osteitis. 발치 후 <strong>3~5일에 강한 통증</strong>. 상처 소독·의료용 거즈로 처치.</p>' ),
		array( '뼈이식', 'implant', '골이식과 동일 · 부족한 뼈 보강', '<p>Bone Graft. 임플란트 식립·발치 부위 재건에 사용. 자가골·동종골·이종골·합성골.</p>' ),
		array( '이종골 이식재', 'implant', '동물 뼈에서 유래한 골이식재', '<p>주로 소·돼지 뼈 유래. <strong>Bio-Oss</strong>가 대표. 오랜 흡수 시간, 골 형태 유지 우수.</p>' ),
		array( '콜라겐 멤브레인', 'implant', 'GBR·GTR에 사용하는 흡수성 차폐막', '<p>Collagen Membrane. 흡수성이라 <strong>제거 수술 불필요</strong>. Bio-Gide 대표 브랜드.</p>' ),
		array( '차단막', 'implant', 'GBR에서 골이식재를 보호하는 막', '<p>Barrier Membrane. 흡수성·비흡수성. 골재생 부위에 <strong>연조직 침투 차단</strong>.</p>' ),
		array( '본 시멘트', 'implant', '골이식재를 고정하는 시멘트', '<p>Bone Cement. 골이식재·차단막을 <strong>고정</strong>하는 데 사용.</p>' ),
		array( '노인 임플란트 보험', 'implant', '만 65세 이상 평생 2개', '<p>건강보험 대상. 본인부담 약 30%. PFM·지르코니아 크라운.</p>' ),
		array( '디지털 임플란트', 'implant', '디지털 워크플로우 기반 임플란트', '<p>CBCT + 구강 스캔 + CAD/CAM으로 진단·설계·수술·보철 전 과정 디지털화.</p>' ),
		array( '네오 (NeoBiotech)', 'implant', '국산 임플란트 브랜드 · IS/CMI 시스템', '<p>NeoBiotech. 국산 프리미엄 임플란트. IS·CMI 시스템으로 초기 고정력·심미성 우수.</p>' ),
		array( '커스텀 어버트먼트', 'implant', '맞춤형 지대주와 동일 · CAD/CAM 제작', '<p>Custom Abutment. 환자별 잇몸·치아 형태에 맞춰 CAD/CAM 제작.</p>' ),
		array( '임플란트 시멘트 vs 스크류', 'implant', '보철 유지 방식 두 가지', '<p>시멘트 유지: 심미부·부드러움. 스크류 유지: <strong>탈착 가능</strong>·잔여 시멘트 걱정 없음.</p>' ),
		array( '보철 시적', 'implant', '최종 크라운 시 정기 확인', '<p>Try-in. 최종 보철 완성 후 <strong>구강 내에서 적합도·색·교합 확인</strong>. 필요 시 미세 수정.</p>' ),

		/* ==================== 교정 (추가) ==================== */
		array( '1급 부정교합', 'ortho', '앞·뒤 관계는 정상, 부분 배열 이상', '<p>Class I. 어금니 <strong>맞물림은 정상</strong>이나 앞니 총생·회전 등 국소적 배열 이상.</p>' ),
		array( '2급 부정교합', 'ortho', '위턱이 앞으로 나온 부정교합 (돌출입)', '<p>Class II. <strong>상악이 하악보다 앞</strong>. 안모상 돌출입 경향. 앙글 분류 기준.</p>' ),
		array( '3급 부정교합', 'ortho', '아래턱이 앞으로 나온 부정교합 (주걱턱)', '<p>Class III. <strong>하악이 상악보다 앞</strong>. 주걱턱·반대교합. 성장기 조기 교정 중요.</p>' ),
		array( '교정 고무줄', 'ortho', '치아 이동력을 만드는 얇은 고무링', '<p>Elastic Band. 브라켓 간·상하악에 걸어 <strong>추가 힘</strong> 생성. 환자 협조 필수.</p>' ),
		array( '클리어얼라이너 부착물', 'ortho', '치아 표면에 붙이는 미세 돌기', '<p>Attachment. 투명교정 시 얼라이너가 <strong>미끄러지지 않게</strong> 붙이는 레진 돌기. 심미성 유지.</p>' ),
		array( '메탈 브래킷', 'ortho', '스테인리스 스틸 브라켓', '<p>Metal Bracket. 가장 <strong>강도·안정성 우수</strong>. 심미성은 낮음. 청소년에 주로 사용.</p>' ),
		array( '세라믹 브래킷', 'ortho', '치아색 세라믹 브라켓', '<p>Ceramic Bracket. 치아와 <strong>비슷한 색</strong>으로 심미성 향상. 파절 위험 있음.</p>' ),
		array( '셀프 라이게이팅 브래킷', 'ortho', '고무줄 없이 슬라이딩 도어로 와이어 고정', '<p>Self-Ligating. 마찰이 적어 <strong>이동 속도 향상</strong>, 조정 간격 연장.</p>' ),
		array( '클리피씨', 'ortho', 'Tomy사의 자가결찰 브라켓 브랜드', '<p>Clippy-C. 일본 Tomy의 <strong>세라믹 자가결찰</strong> 브라켓. 심미성·마찰 감소.</p>' ),
		array( '교정용 와이어', 'ortho', '치아 이동력을 전달하는 아치 와이어', '<p>Archwire. NiTi(니티놀)·스테인리스·베타티타늄. <strong>단계별로 굵기·소재 변경</strong>.</p>' ),
		array( '교정 밴드', 'ortho', '어금니에 감는 금속 링', '<p>Molar Band. 어금니 <strong>주위를 감싸는 링</strong>. 튜브가 부착되어 와이어 고정.</p>' ),
		array( '교정 왁스', 'ortho', '브라켓 자극 완화용 왁스', '<p>Orthodontic Wax. 브라켓·와이어가 볼 안쪽을 <strong>찌를 때 붙이는 왁스</strong>. 상처 예방.</p>' ),
		array( '교정 외상', 'ortho', '교정 장치로 인한 구강 내 상처', '<p>브라켓·와이어에 의한 <strong>볼·입술·혀 상처</strong>. 왁스·즉시 조정으로 처치.</p>' ),
		array( '교정 중 관리', 'ortho', '장치 부착 중 구강 위생 관리', '<p>치실·치간 칫솔·워터픽 필수. 잇몸 염증·<strong>브라켓 주변 충치</strong> 예방.</p>' ),
		array( '교정 중 구강 관리', 'ortho', '교정 장치 착용 중 위생 팁', '<p>매 식사 후 양치·치간 청소. <strong>단단·끈적한 음식 피하기</strong>. 정기 조정 방문.</p>' ),
		array( '투명 교정장치', 'ortho', '얼라이너 통칭', '<p>Clear Aligner. 인비절라인·슈어스마일·PMD 등. <strong>탈부착 가능</strong>, 심미성 우수.</p>' ),
		array( '소아 교정', 'ortho', '성장기 아동 교정', '<p>1단계(6~10세)·2단계(11세~영구치 완료). <strong>성장 잠재력</strong> 활용, 골격 문제 해결에 유리.</p>' ),
		array( '악교정 수술', 'ortho', '골격 부조화 교정 수술', '<p>Orthognathic Surgery. 심한 주걱턱·무턱·비대칭에 <strong>턱뼈 수술 + 교정</strong> 조합. 양악 수술 대표.</p>' ),
		array( '안면 비대칭', 'ortho', '얼굴 좌우가 비대칭인 상태', '<p>Facial Asymmetry. 골격성 원인은 <strong>악교정 수술</strong> 필요. 경미하면 교정만으로 개선.</p>' ),
		array( '정중선 불일치', 'ortho', '위·아래 치아 정중선이 어긋난 상태', '<p>Midline Deviation. 상하 <strong>정중선 어긋남</strong>. 심미·기능 문제 발생 시 교정.</p>' ),
		array( '치아 함입', 'ortho', '외상 등으로 치아가 잇몸 속으로 밀려 들어감', '<p>Tooth Intrusion. 외상성. <strong>자연 재출력 대기</strong> 또는 교정력으로 재위치.</p>' ),
		array( '치아 정출', 'ortho', '치아가 원래 위치보다 튀어나온 상태', '<p>Tooth Extrusion. 대합치 결손 등으로 <strong>맞물릴 상대가 없어 튀어나옴</strong>. 교정·삭제·크라운.</p>' ),
		array( '치아 탈구', 'ortho', '외상으로 치아가 정상 위치를 벗어남', '<p>Tooth Luxation. 완전 탈구·부분 탈구. <strong>즉시 재위치·고정</strong>이 예후 좌우.</p>' ),
		array( '치아 변위', 'ortho', '치아가 원래 위치를 벗어난 상태', '<p>Tooth Displacement. 외상·습관·부정교합으로 <strong>정상 위치 이탈</strong>.</p>' ),
		array( '과잉치', 'ortho', '정상 치아 수보다 많이 나는 치아', '<p>Supernumerary Tooth. <strong>메시오덴스</strong>(앞니 사이) 가장 흔함. 발치 대상.</p>' ),
		array( '왜소치', 'ortho', '평균보다 작은 치아 · 주로 측절치', '<p>Peg lateral. <strong>측절치가 작아 못처럼 뾰족한 형태</strong>. 라미네이트·크라운으로 심미 회복.</p>' ),
		array( '융합치', 'ortho', '두 치아가 발생 단계에서 합쳐진 것', '<p>Fused Tooth. 발생 초기 <strong>두 치아 배아가 융합</strong>. 유치·영구치 모두 발생 가능.</p>' ),
		array( '쌍생치', 'ortho', '하나의 치아가 두 개로 나뉜 형태', '<p>Geminated Tooth. 하나의 치아가 <strong>두 개의 치관</strong>으로 발육. 뿌리는 하나.</p>' ),
		array( '치아 형태 수정', 'ortho', '치아 모양을 소량 삭제로 다듬음', '<p>Reshaping. 앞니 각도·모양을 <strong>0.1~0.5mm 삭제</strong>로 조정. 통증 없음.</p>' ),

		/* ==================== 보존·신경 (추가) ==================== */
		array( '치근 천공', 'preserve', '신경치료 중 치근에 구멍이 뚫린 사고', '<p>Root Perforation. 파일·기구로 <strong>치근에 구멍</strong>이 생김. MTA로 봉쇄하거나 발치.</p>' ),
		array( '파일 파절', 'preserve', '신경치료 중 파일이 신경관 안에서 부러짐', '<p>File Separation. <strong>NiTi 파일이 부러져</strong> 신경관 내부에 남음. 제거 시도·우회·발치 결정.</p>' ),
		array( '근관 재치료', 'preserve', '재근관치료와 동일 · 실패 신경치료 재시도', '<p>이전 근관치료 실패 시 <strong>기존 충전재 제거 후</strong> 재세척·재충전.</p>' ),
		array( '재신경치료', 'preserve', '근관 재치료와 동일', '<p>실패한 신경치료를 다시 시도. 성공률 80%+, 정밀 진단 필요.</p>' ),
		array( '의도적 재식술', 'preserve', '치아를 뽑았다가 재식립하는 최후의 신경치료', '<p>Intentional Replantation. 재근관치료 불가 시 <strong>발치 → 근관 처리 → 재식</strong>. 최후의 수단.</p>' ),
		array( '치아 균열 증후군', 'preserve', '치아에 미세 균열이 있어 씹을 때 통증', '<p>Cracked Tooth Syndrome. <strong>씹을 때만 순간적 예리한 통증</strong>. 조기 발견이 발치 예방.</p>' ),
		array( '치아 파절 (외상)', 'preserve', '외상으로 치아가 부러진 상태', '<p>파절 부위·깊이별 처치: <strong>레진·크라운·신경치료·발치</strong>. 24시간 내 응급 처치.</p>' ),
		array( '치아 변색 (외상성)', 'preserve', '외상으로 치아 색이 어두워짐', '<p>Traumatic Discoloration. 외상 후 <strong>치수 손상으로 어둡게 변색</strong>. 신경치료·워킹 블리치.</p>' ),
		array( '내부 미백 (워킹 블리치)', 'preserve', '신경치료된 치아 내부를 미백', '<p>Walking Bleach. 신경치료 후 어두워진 치아 <strong>내부에 미백제</strong>. 1~2주 후 확인.</p>' ),
		array( '치아 변색', 'preserve', '치아 색이 어두워지는 원인·치료', '<p>내인성(신경치료·약물)·외인성(음식·흡연). 미백·라미네이트·크라운으로 개선.</p>' ),
		array( '이차 우식', 'preserve', '기존 충전물 주변에 재발한 충치', '<p>Secondary Caries. 기존 보철·충전물 <strong>변연 미세 틈</strong>에서 세균 침투로 재발.</p>' ),
		array( '노인 뿌리 우식', 'preserve', '잇몸 퇴축으로 노출된 치근에 발생', '<p>Root Caries. 시니어에 흔함. <strong>불소도포·시린이 관리·정기 검진</strong>이 예방.</p>' ),
		array( '수산화칼슘', 'preserve', '신경치료·치수복조에 사용하는 재료', '<p>Ca(OH)₂. <strong>항균·재광화</strong>. 임시 근관 충전·직접치수복조 등에 사용.</p>' ),
		array( '광중합기', 'preserve', '레진 경화용 파란색 광 장치', '<p>Curing Light. 파란 LED 광으로 <strong>레진 광경화</strong>. 20초 이내 경화 완료.</p>' ),
		array( '본딩제', 'preserve', '레진을 치아에 접착시키는 접착제', '<p>Bonding Agent. 레진 충전 전 치아 표면에 도포해 <strong>강한 결합력</strong>. Etch-and-rinse·Self-etch.</p>' ),
		array( '복합레진', 'preserve', '심미레진과 동일 · 광경화 레진', '<p>Composite Resin. 광경화 <strong>복합 수지</strong>. 충치·심미치료에 널리 사용.</p>' ),
		array( '컴포짓 레진', 'preserve', '복합레진과 동일', '<p>Composite Resin. 폴리머 매트릭스에 실리카·글래스 필러 첨가. 강도·심미성 우수.</p>' ),
		array( '레진', 'preserve', '치과용 광중합 수지 통칭', '<p>치과 <strong>충전·심미·본딩</strong>에 광범위 사용. 광경화·자가경화·이중경화.</p>' ),
		array( '레진 인레이', 'preserve', '레진 소재의 간접 수복 인레이', '<p>Resin Inlay. 세라믹보다 <strong>저렴·심미성 양호</strong>. 큰 충치에 적합.</p>' ),
		array( '글래스 아이오노머', 'preserve', '불소 방출 시멘트/충전재 (GIC)', '<p>Glass Ionomer Cement. <strong>불소 방출·화학적 결합</strong>. 유치·치경부 충치·임시 충전에 사용.</p>' ),
		array( 'MTA (미네랄 트리옥사이드)', 'preserve', '신경치료·치수보존 첨단 재료', '<p>Mineral Trioxide Aggregate. 생체친화적, <strong>봉쇄력 우수</strong>. 치근천공·역행성 근관치료·치수복조.</p>' ),
		array( '구타페르카', 'preserve', '거타퍼차와 동일 · 신경관 최종 충전재', '<p>Gutta-percha. 신경관 밀봉 재료. 씰러와 함께 사용.</p>' ),
		array( '치수', 'preserve', '치아 내부 신경·혈관 조직', '<p>Pulp. 치아 신경·혈관. 치수염 → 신경치료 대상.</p>' ),
		array( '치수 괴사', 'preserve', '치수가 죽어버린 상태', '<p>Pulp Necrosis. 방치하면 <strong>근단 농양</strong>으로 진행. 즉시 신경치료 필요.</p>' ),
		array( '치수염', 'preserve', '치수의 염증 · 가역·비가역', '<p>Pulpitis. 가역성(회복 가능)·비가역성(신경치료 필요) 구분.</p>' ),
		array( '치근단', 'preserve', '치아 뿌리 끝 부위', '<p>Apex. 치근의 끝. <strong>신경·혈관이 드나드는 유공</strong>.</p>' ),
		array( '바이탈리티 테스트', 'preserve', '치수 생존 여부 검사', '<p>Vitality Test. <strong>냉·열·전기 자극</strong>으로 치수 반응 확인. 신경치료 필요성 판단.</p>' ),
		array( '타악', 'preserve', '치아 두드림으로 통증 확인', '<p>Percussion. 기구로 <strong>치아를 두드려</strong> 치근 주위 염증 여부 확인.</p>' ),

		/* ==================== 치주 (추가) ==================== */
		array( '치주낭', 'periodontics', '치주 포켓과 동일 · 잇몸과 치아 사이 공간', '<p>Periodontal Pocket. 정상은 1~3mm. <strong>4mm 이상이면 치주염</strong>.</p>' ),
		array( '치주 재생술', 'periodontics', '소실된 치주 조직 재생 유도', '<p>Regeneration Therapy. 골이식·GTR·성장인자로 <strong>치조골·치주인대·시멘트질 재생</strong>.</p>' ),
		array( '치근 피개술', 'periodontics', '노출된 치근을 잇몸으로 덮는 수술', '<p>Root Coverage. 잇몸 퇴축으로 노출된 치근을 <strong>인접 잇몸 이동·이식</strong>으로 덮음.</p>' ),
		array( '치주 유지관리', 'periodontics', 'SPT · 재발 방지 정기 관리', '<p>Supportive Periodontal Therapy. 치주치료 후 <strong>3~6개월 간격 정기</strong> 관리.</p>' ),
		array( '치주 수술 후 관리', 'periodontics', '수술 후 회복·재발 방지', '<p>1주 강한 양치 자제·부드러운 음식·항생제·정기 세척. <strong>2주 후 실밥 제거</strong>.</p>' ),
		array( '치은 이식 종류', 'periodontics', '유리치은·결합조직 이식 등', '<p>FGG(유리치은 이식)·CTG(결합조직 이식)·터널 테크닉 등 <strong>목적별 선택</strong>.</p>' ),
		array( '치은 이식술', 'periodontics', '잇몸 이식과 동일', '<p>Gum Grafting. 잇몸 퇴축·부착치은 부족에 이식.</p>' ),
		array( '치은 절제술', 'periodontics', '잇몸을 절제해 라인 조정', '<p>Gingivectomy. 잇몸 <strong>과증식·불규칙 라인 절제</strong>. 심미·기능 개선.</p>' ),
		array( '잇몸 절제술', 'periodontics', '치은 절제술과 동일', '<p>레이저 또는 메스로 잇몸을 절제. 회복 1~2주.</p>' ),
		array( '치은 비대', 'periodontics', '잇몸이 비정상적으로 커진 상태', '<p>Gingival Hyperplasia. <strong>약물성·유전성</strong>. 잇몸 절제술로 개선.</p>' ),
		array( '약물성 치은 증식', 'periodontics', '항간질약·면역억제제 등 약물 부작용', '<p>Drug-induced Gingival Overgrowth. <strong>페니토인·사이클로스포린·니페디핀</strong> 등 원인.</p>' ),
		array( '임신성 치은염', 'periodontics', '임신 중 호르몬 변화로 심해지는 치은염', '<p>Pregnancy Gingivitis. <strong>호르몬으로 잇몸 예민</strong>. 스케일링·구강위생으로 관리.</p>' ),
		array( '치은 출혈', 'periodontics', '잇몸 출혈과 동일', '<p>Gingival Bleeding. 치은염·치주염의 대표 증상. 조기 대응 필수.</p>' ),
		array( '치은열구', 'periodontics', '정상 잇몸과 치아 사이 좁은 홈', '<p>Gingival Sulcus. 정상 깊이 <strong>1~3mm</strong>. 4mm 넘으면 치주낭.</p>' ),
		array( '치은', 'periodontics', '잇몸의 의학 용어', '<p>Gingiva. 치아를 감싸고 있는 <strong>구강 점막</strong>.</p>' ),
		array( '치은염', 'periodontics', '잇몸에 국한된 초기 염증', '<p>Gingivitis. 치석·치태로 인한 <strong>잇몸 표면 염증</strong>. 회복 가능한 초기 단계.</p>' ),
		array( '치주 농양', 'periodontics', '치주 포켓 안 화농성 염증', '<p>Periodontal Abscess. 심한 잇몸 통증·부기·고름. 즉시 배농·항생제.</p>' ),
		array( '치주 스플린트', 'periodontics', '흔들리는 치아를 인접 치아와 연결', '<p>Splinting. 치주염으로 <strong>흔들리는 치아를 인접 치아와 결합</strong>해 안정화.</p>' ),
		array( '부착치은', 'periodontics', '치아에 단단히 붙어있는 각화 잇몸', '<p>Attached Gingiva. 치아 뿌리와 <strong>단단히 결합된 잇몸</strong>. 부족 시 이식 필요.</p>' ),
		array( '잇몸 색소침착', 'periodontics', '멜라닌 등으로 잇몸이 검게 됨', '<p>Gingival Pigmentation. 인종·흡연·약물 원인. <strong>잇몸 미백(레이저)</strong>으로 개선.</p>' ),
		array( 'BOP (탐침 시 출혈)', 'periodontics', '치주 검사의 핵심 지표', '<p>Bleeding on Probing. 프로빙 시 <strong>출혈 여부</strong>. 활동성 치주염 지표.</p>' ),
		array( '프로빙', 'periodontics', '치주 포켓 깊이 측정', '<p>Probing. 치주 프로브로 <strong>치주낭 깊이 mm 측정</strong>. 치주 진단 기본.</p>' ),
		array( '플라크 지수', 'periodontics', '치태 축적 정도를 수치화', '<p>Plaque Index (PI). 치아 표면 <strong>치태 양을 0~3점</strong>으로 평가. 위생 상태 추적.</p>' ),

		/* ==================== 심미치료 (추가) ==================== */
		array( '라미네이트 종류', 'aesthetic', 'e.max·Empress·No-prep·Minimal 등', '<p>재료·삭제량 기준: <strong>e.max·Empress·지르코니아·No-prep·최소침습</strong> 라미네이트.</p>' ),
		array( '치아 미백', 'aesthetic', '치아를 밝게 만드는 시술 통칭', '<p>홈·오피스·복합 미백. 과산화수소 기반. <strong>1~2년 후 재착색</strong> 가능.</p>' ),
		array( '블리칭', 'aesthetic', '치아 미백의 영문 표현', '<p>Bleaching. 치아 미백과 동일. 내부 미백(워킹 블리치) 포함.</p>' ),
		array( '치아 탈색', 'aesthetic', '치아 색을 밝게 하는 표백', '<p>과산화수소·과산화요소로 <strong>색소 분자를 분해</strong>. 자연치만 가능, 보철물 X.</p>' ),
		array( '치아 색상 측정', 'aesthetic', '보철 제작을 위한 정확한 색 매칭', '<p>Vita Shade Guide·<strong>디지털 색상 측정기</strong>. 정확한 색을 기공소에 전달.</p>' ),
		array( '보철 색조 선택', 'aesthetic', '주변 자연치와 조화되는 색 결정', '<p>Shade Selection. 자연광·주변 치아 색과의 조화가 중요. <strong>디지털 사진·측정기</strong> 활용.</p>' ),
		array( '치아 흔들림', 'aesthetic', '치주염·외상·과부하로 흔들리는 치아', '<p>Mobility. 원인 파악 후 <strong>스플린트·치주치료·발치</strong> 결정.</p>' ),
		array( 'DSD (디지털 스마일 디자인)', 'aesthetic', 'PC로 미리 스마일 디자인', '<p>Digital Smile Design. 사진·구강 스캔으로 <strong>결과를 미리 시뮬레이션</strong>. 환자 만족도 향상.</p>' ),
		array( '디지털 스마일 디자인', 'aesthetic', 'DSD와 동일', '<p>디지털 시뮬레이션으로 심미 치료 결과 예측.</p>' ),
		array( '보툴리눔', 'aesthetic', '보톡스와 동일 · A형 독소', '<p>Botulinum Toxin A. 근육을 <strong>일시적으로 마비</strong>시켜 사각턱 축소·이갈이·거미스마일 개선.</p>' ),

		/* ==================== 보철 (추가) ==================== */
		array( '골드 크라운', 'prosthetics', '금 합금 크라운 · 어금니 표준', '<p>Gold Crown. <strong>강도·적합도·수명 최고</strong>. 심미성은 낮음. 어금니에 적합.</p>' ),
		array( '지르코니아', 'prosthetics', '산화 지르코늄 세라믹 소재', '<p>Zirconia. 강도·심미·생체친화성. <strong>크라운·임플란트·라미네이트</strong> 등 광범위 사용.</p>' ),
		array( 'e.max (이맥스)', 'prosthetics', '이보클라 리튬 디실리케이트 세라믹', '<p>Ivoclar 사의 <strong>리튬 디실리케이트</strong>. 심미성·강도 균형. 라미네이트·크라운 표준.</p>' ),
		array( '세라믹', 'prosthetics', '치과용 세라믹 통칭', '<p>Ceramic. <strong>지르코니아·리튬 디실리케이트(e.max)·글래스 세라믹</strong> 등.</p>' ),
		array( '하이브리드 세라믹', 'prosthetics', '레진과 세라믹 혼합 재료', '<p>Hybrid Ceramic. 세라믹 강도 + 레진 유연성. <strong>Cerasmart·Vita Enamic</strong> 대표.</p>' ),
		array( '온레이', 'prosthetics', '치아 씹는 면 넓게 덮는 부분 보철', '<p>Onlay. 인레이보다 <strong>더 넓은 부위</strong>(교두 포함) 덮음. 크라운보다 보존적.</p>' ),
		array( 'PEEK', 'prosthetics', '치과용 폴리머 · 금속 알레르기 대안', '<p>Polyether Ether Ketone. 강도·생체친화·금속 알레르기 없음. <strong>임플란트 상부·틀니</strong> 프레임에 사용.</p>' ),
		array( 'PMMA', 'prosthetics', '치과용 아크릴 수지', '<p>Polymethyl Methacrylate. <strong>임시 크라운·틀니 base·CAD/CAM 밀링</strong>에 널리 사용.</p>' ),
		array( '섬유 강화 복합레진', 'prosthetics', '유리섬유 등으로 강화된 레진', '<p>Fiber-Reinforced Composite. <strong>브릿지 프레임·포스트</strong>에 사용. 유연성·심미성.</p>' ),
		array( '완전 틀니', 'prosthetics', '전체 무치악에 사용하는 총의치', '<p>Complete Denture. 모든 치아 상실 시 <strong>착탈식 인공 치아</strong>. 65세 이상 보험.</p>' ),
		array( '부분 틀니', 'prosthetics', '일부 치아를 잃은 경우의 착탈식 보철', '<p>Partial Denture. <strong>클라스프로 남은 치아</strong>에 걸어 안정.</p>' ),
		array( '틀니 관리법', 'prosthetics', '틀니의 매일 청소·보관', '<p>매일 <strong>전용 세정제로 세척</strong>, 물에 보관 (건조 방지). 잠자기 전 제거.</p>' ),
		array( '노인 의치 적응', 'prosthetics', '틀니 착용 초기 적응 팁', '<p>부드러운 음식·소량씩 씹기·발음 연습. <strong>2~4주 적응 기간</strong>. 통증 시 즉시 조정.</p>' ),
		array( '의치 안정제', 'prosthetics', '틀니 유지력 보강제 (크림·파우더)', '<p>Denture Adhesive. 폴리그립·픽스오덴탈. <strong>맞지 않는 틀니는 재제작</strong> 필요.</p>' ),
		array( '리베이스', 'prosthetics', '틀니 내면을 새로 만들어 다시 맞춤', '<p>Rebase. 잇몸이 <strong>흡수로 틀니가 헐거워졌을 때</strong> 내면을 재제작.</p>' ),
		array( '클래스프', 'prosthetics', '부분 틀니를 지지 치아에 걸어 고정하는 금속 고리', '<p>Clasp. 부분 틀니의 <strong>지지·유지</strong> 역할. 금속·심미 클라스프.</p>' ),
		array( '지대치', 'prosthetics', '브릿지·부분틀니의 지지 치아', '<p>Abutment Tooth. 브릿지·부분틀니를 <strong>지지·유지</strong>하는 자연치.</p>' ),
		array( '폰틱', 'prosthetics', '브릿지에서 결손 치아를 대체하는 인공치', '<p>Pontic. 브릿지의 <strong>중간 인공 치아</strong>. 지대치 사이에 걸침.</p>' ),
		array( '포스트 코어', 'prosthetics', '신경치료 후 크라운을 위한 기둥·코어', '<p>Post & Core. 신경치료로 <strong>약해진 치아에 지주 삽입</strong> 후 코어로 크라운 지지.</p>' ),
		array( '마진 (보철 변연)', 'prosthetics', '크라운 아래쪽 잇몸과 만나는 경계', '<p>Margin. <strong>변연 적합도가 보철 수명 좌우</strong>. 잘못하면 이차 우식 발생.</p>' ),
		array( '임시 시멘트', 'prosthetics', '임시 크라운용 약접착 시멘트', '<p>Temporary Cement. <strong>탈부착 용이</strong>. Zinc Oxide Eugenol 계열.</p>' ),
		array( '치과용 시멘트', 'prosthetics', '크라운·인레이 접착제 통칭', '<p>Dental Cement. <strong>RelyX·GC Fuji·Ketac Cem·Zinc Phosphate</strong> 등.</p>' ),
		array( '인상재', 'prosthetics', '치아 본을 뜨는 재료', '<p>Impression Material. 알지네이트·실리콘·폴리에테르. <strong>정밀도·용도별 선택</strong>.</p>' ),
		array( '인상재 종류', 'prosthetics', 'PVS·폴리에테르·알지네이트 등', '<p>PVS(정밀)·폴리에테르(친수성)·알지네이트(간이). <strong>보철 종류별</strong> 다른 재료.</p>' ),
		array( '왁스', 'prosthetics', '보철 제작·바이트 등록용 왁스', '<p>Dental Wax. 바이트 왁스·<strong>왁스업</strong> 등 다양한 용도.</p>' ),
		array( '석고', 'prosthetics', '모형 제작용 치과용 석고', '<p>Gypsum. 인상으로부터 <strong>모형 제작</strong>. Type I~V 강도별 분류.</p>' ),
		array( '교합기', 'prosthetics', '위·아래 턱의 관계를 재현하는 장치', '<p>Articulator. 반조절성·완전조절성. <strong>보철 제작·교정 진단</strong>에 사용.</p>' ),
		array( '대합치', 'prosthetics', '반대편 턱에서 맞물리는 치아', '<p>Opposing Tooth. 위 어금니의 대합치는 <strong>같은 위치 아래 어금니</strong>. 대합치 없으면 정출 위험.</p>' ),
		array( '교합', 'prosthetics', '위·아래 치아가 맞물리는 관계', '<p>Occlusion. 정상 교합·부정교합. 보철·교정의 <strong>궁극 목표</strong>.</p>' ),
		array( '교합 조정', 'prosthetics', '보철 후 씹는 접촉 조정', '<p>Occlusal Adjustment. 보철 부착 후 <strong>포일로 접촉점 확인·미세 조정</strong>.</p>' ),
		array( '중절치', 'prosthetics', '앞니 중 가장 가운데 위치한 치아', '<p>Central Incisor. 상하 각 2개, 총 4개. <strong>얼굴 인상 결정</strong>하는 핵심 치아.</p>' ),
		array( '견치', 'prosthetics', '송곳니와 동일', '<p>Canine. 뾰족한 <strong>4번째 치아</strong>. 안모 형성·저작에 중요.</p>' ),
		array( '절치', 'prosthetics', '앞니 · 음식 절단', '<p>Incisor. 위·아래 <strong>중절치·측절치</strong> 각 4개씩 총 8개.</p>' ),

		/* ==================== 구강외과 (추가) ==================== */
		array( '단순 발치', 'surgery', '노출된 치아를 뽑는 기본 시술', '<p>Simple Extraction. 잇몸 위로 나온 치아를 <strong>15분 이내</strong> 시술.</p>' ),
		array( '복잡 발치', 'surgery', '외과적 발치와 동일', '<p>Complex Extraction. 잇몸 절개·<strong>뼈 다듬음</strong> 필요한 발치.</p>' ),
		array( '발치', 'surgery', '치아를 뽑는 시술 통칭', '<p>Extraction. 단순·외과적 발치. <strong>사랑니·심한 충치·치주염</strong> 대상.</p>' ),
		array( '발치 후 통증', 'surgery', '정상 통증 vs 드라이 소켓', '<p>보통 <strong>2~3일 후 감소</strong>. 3~5일 후 심해지면 드라이 소켓 의심.</p>' ),
		array( '발치 후 출혈', 'surgery', '거즈 압박으로 지혈', '<p>발치 후 <strong>1시간 거즈 압박</strong>. 지속 시 재방문. 항응고제 복용자 주의.</p>' ),
		array( '발치 후 주의사항', 'surgery', '침 뱉기·빨대·흡연 금지', '<p>1주간 <strong>강한 헹굼·침 뱉기·빨대·흡연·음주 금지</strong>. 부드러운 음식.</p>' ),
		array( '입술 열상', 'surgery', '외상으로 입술이 찢어진 상처', '<p>Lip Laceration. 응급 시 <strong>봉합</strong>. 감염·흉터 최소화가 목표.</p>' ),
		array( '점액낭종', 'surgery', '입술·볼 안쪽에 생긴 물주머니', '<p>Mucocele. 침샘관 손상으로 <strong>침이 고이는 물주머니</strong>. 외과적 절제.</p>' ),
		array( '납종', 'surgery', '입안 점막에 생긴 만성 궤양', '<p>Lipoma. 지방 세포 종양. 크면 절제.</p>' ),
		array( '타석증', 'surgery', '침샘관에 결석이 형성된 상태', '<p>Sialolithiasis. 침샘관 <strong>결석으로 침 배출 방해</strong>. 통증·부기. 외과적 제거.</p>' ),
		array( '악골 골수염', 'surgery', '턱뼈에 발생한 감염성 골수 염증', '<p>Osteomyelitis. <strong>발치·감염·외상</strong> 후 발생 가능. 항생제·수술.</p>' ),
		array( '골괴사', 'surgery', '턱뼈가 죽는 심각한 합병증', '<p>Osteonecrosis. <strong>BRONJ·방사선 골괴사</strong>. 예방이 최우선.</p>' ),
		array( 'BRONJ (약물 관련 턱뼈 괴사)', 'surgery', '비스포스포네이트 부작용', '<p>Bisphosphonate-Related Osteonecrosis of Jaw. <strong>골다공증 약제</strong> 복용자 발치 후 위험.</p>' ),
		array( '비스포스포네이트', 'surgery', '골다공증·항암 치료제', '<p>Bisphosphonate. <strong>골 흡수 억제제</strong>. 장기 복용 시 턱뼈 괴사 위험.</p>' ),
		array( '구강암', 'surgery', '구강 내 악성 종양', '<p>Oral Cancer. 혀·잇몸·볼·입천장 발생. <strong>2주 이상 낫지 않는 궤양</strong> 시 검진.</p>' ),
		array( '구강암 자가검진', 'surgery', '월 1회 입안 자가 관찰', '<p>혀·잇몸·볼·입천장에 <strong>흰 반점·붉은 반점·궤양·혹</strong> 확인. 이상 시 즉시 검진.</p>' ),
		array( '구강암 조기 징후', 'surgery', '흰/붉은 반점·궤양·혹', '<p>2주 이상 <strong>낫지 않는 궤양·통증 없는 혹</strong>·발음 이상. 조기 발견이 생존율 결정.</p>' ),
		array( '백반증', 'surgery', '구강 점막에 생기는 흰 병변', '<p>Leukoplakia. <strong>흰 반점</strong>. 일부 악성 전환 가능. 조직검사 필요.</p>' ),
		array( '홍반증', 'surgery', '구강 점막에 생기는 붉은 병변', '<p>Erythroplakia. <strong>붉은 반점</strong>. 백반증보다 악성 위험 높음. 즉시 검사.</p>' ),
		array( '편평태선', 'surgery', '자가면역성 구강 점막 질환', '<p>Lichen Planus. 볼 안쪽·혀에 <strong>흰 줄무늬·궤양</strong>. 스테로이드 관리.</p>' ),
		array( '수포성 질환', 'surgery', '입안에 물집·궤양 반복', '<p>Pemphigus·Pemphigoid 등. <strong>자가면역성</strong>. 조직검사·면역 억제 치료.</p>' ),
		array( '치성 감염', 'surgery', '치아 원인 세균 감염', '<p>Odontogenic Infection. 충치·치주염·근단 농양 → <strong>주변 조직·전신 확산</strong> 위험.</p>' ),
		array( '치과 감염관리', 'surgery', '병원 감염 예방 프로토콜', '<p>Infection Control. 모든 기구 <strong>멸균</strong>, 일회용품 사용, 개인보호구.</p>' ),
		array( '교차 감염', 'surgery', '환자 간 병원체 전파 위험', '<p>Cross Infection. <strong>기구 멸균·소독·일회용품</strong>으로 예방.</p>' ),
		array( '오토클레이브 멸균', 'surgery', '고압증기 멸균 (표준 방법)', '<p>Autoclave. <strong>121~134℃ 고압 증기</strong>로 완전 멸균. 치과 표준.</p>' ),
		array( '일회용 기구', 'surgery', '환자별 새것 사용 후 폐기', '<p>Disposable. 주사바늘·거즈·석션팁 등. <strong>재사용 없음</strong>.</p>' ),
		array( '멸균 시스템', 'surgery', '오토클레이브 + 초음파 세척', '<p>초음파 세척 → 소독 → 오토클레이브 → 무균 포장. <strong>ISO 감염관리 기준</strong>.</p>' ),
		array( '의료폐기물', 'surgery', '치과에서 배출되는 감염성 폐기물', '<p>주사바늘·거즈·발치된 치아 등. <strong>전용 통·전문 업체 처리</strong>.</p>' ),
		array( '치과 응급 상황', 'surgery', '외상·심한 통증·부기 등', '<p>치아 완전 탈구·심한 부기·외상. <strong>즉시 응급실 또는 야간 치과</strong>.</p>' ),

		/* ==================== 턱관절 (추가) ==================== */
		array( '턱관절 디스크', 'tmj', '관절원판과 동일', '<p>턱관절 안의 <strong>섬유 연골 디스크</strong>. 저작 시 완충 역할.</p>' ),
		array( '턱관절 디스크 변위', 'tmj', '관절원판 변위와 동일', '<p>Disc Displacement. 입 벌릴 때 소리·통증. 자기 위치 회복 or 지속.</p>' ),
		array( '턱에서 소리', 'tmj', '딱딱·뚝·긁는 소리', '<p>Clicking·Popping·Crepitus. <strong>디스크 변위·관절 마모</strong> 신호. 진찰 필요.</p>' ),
		array( '만성 두통과 턱관절', 'tmj', '턱관절이 원인인 두통', '<p>TMJ Headache. 관자놀이·목·어깨 통증 동반. <strong>이갈이·이악물기</strong>가 흔한 원인.</p>' ),
		array( '삼차신경통', 'tmj', '얼굴에 극심한 통증 발생', '<p>Trigeminal Neuralgia. <strong>일측 얼굴</strong>에 갑작스런 극통. 신경과·통증의학과 협진.</p>' ),
		array( '턱관절 자가운동', 'tmj', '집에서 하는 턱관절 운동', '<p>Jaw Exercise. 개구 훈련·근육 이완·자세 교정. <strong>스플린트와 병행</strong>.</p>' ),
		array( '턱관절 장애 자가 진단', 'tmj', '입 벌림 폭·소리·통증 체크', '<p>정상 개구 40~50mm. <strong>딱딱 소리·30mm 이하 개구·아침 통증</strong> 시 진료.</p>' ),
		array( '턱관절 주사', 'tmj', '통증 완화 관절 내 주사', '<p>스테로이드·히알루론산 주입. <strong>염증 감소·윤활 개선</strong>.</p>' ),
		array( '이갈이 보톡스', 'tmj', '저작근에 보톡스 주사로 이갈이 완화', '<p>Bruxism Botox. 교근에 <strong>보톡스로 근육 힘 감소</strong>. 3~6개월 효과.</p>' ),
		array( '이갈이 증상', 'tmj', '아침 턱 뻐근·치아 마모·두통', '<p>수면 중 이갈이 신호: <strong>아침 턱 통증·마모된 치아·배우자가 소리 확인</strong>.</p>' ),
		array( '나이트가드', 'tmj', '수면 중 착용하는 이갈이 방지 장치', '<p>Night Guard. 이갈이·이악물기 환자의 <strong>맞춤 마우스가드</strong>. 치아 마모 예방.</p>' ),
		array( '교합 안정장치', 'tmj', '안정위 스플린트 · 턱관절 안정', '<p>Stabilization Splint. 야간 착용으로 <strong>턱관절·근육 안정</strong>.</p>' ),
		array( '교합기 (TMJ)', 'tmj', '턱관절 진단·보철에 사용', '<p>턱관절 움직임을 <strong>기계적으로 재현</strong>하는 장치.</p>' ),

		/* ==================== 소아 (추가) ==================== */
		array( '유치 충치', 'pediatric', '어린이 유치에 발생한 충치', '<p>영구치보다 <strong>진행 빠름</strong>. 방치 시 신경치료·조기 상실.</p>' ),
		array( '어린이 충치 예방', 'pediatric', '실런트·불소·정기 검진', '<p>어린이 큰어금니 나오면 실런트, 3~6개월 불소도포, <strong>6개월 정기 검진</strong>.</p>' ),
		array( '치아 맹출 지연', 'pediatric', '평균보다 늦게 나는 치아', '<p>Eruption Delay. 유전·영양·과잉치·낭종 등 원인. <strong>X-ray로 확인</strong>.</p>' ),
		array( '유치 조기 상실', 'pediatric', '영구치 나오기 전 빠짐', '<p>영구치 <strong>공간 부족 위험</strong>. 공간유지장치 필요.</p>' ),
		array( '핫 앤 피셔 실란트', 'pediatric', '어금니 홈메우기 재료 종류', '<p>Hot·Fissure Sealant. 광경화 실런트·자가경화 실런트. <strong>어금니 홈 완전 밀봉</strong>.</p>' ),
		array( '지도설', 'pediatric', '혀 표면에 지도처럼 얼룩이 생기는 양성 상태', '<p>Geographic Tongue. 혀 표면 <strong>불규칙한 붉은 반점</strong>. 치료 불필요.</p>' ),
		array( '소아 진정치료', 'pediatric', '공포·움직임 심한 아이 진정 치료', '<p>Pediatric Sedation. <strong>아산화질소·경구 진정제</strong>. 전문 소아치과에서만.</p>' ),
		array( '소아 보호대', 'pediatric', '치료 중 아이 움직임 제한', '<p>Papoose Board. 필수적일 때만 <strong>부드러운 랩</strong>으로 안전한 치료 환경 확보.</p>' ),
		array( '행동조절', 'pediatric', 'Tell-Show-Do 등 소아 행동 유도', '<p>Behavior Management. <strong>Tell-Show-Do·긍정 강화</strong>로 아이가 편하게 진료받게.</p>' ),
		array( '어린이 실런트', 'pediatric', '유·영구 어금니 홈메우기', '<p>영구치 큰어금니가 나온 직후 <strong>홈메우기로 충치 예방률 90%+</strong>.</p>' ),
		array( '스케일링 협조', 'pediatric', '어린이 스케일링 협조 유도', '<p>연령·성격별 접근. <strong>Tell-Show-Do</strong>·짧은 시간·긍정 강화.</p>' ),

		/* ==================== 예방·검진 (추가) ==================== */
		array( '정기검진', 'prevention', '6개월 주기 구강 검진', '<p>Regular Check-up. <strong>6개월~1년 주기</strong>. 조기 발견이 최선의 예방.</p>' ),
		array( '정기 검진 주기', 'prevention', '일반 6개월·고위험군 3개월', '<p>일반인 <strong>6개월</strong>. 치주염·임플란트·당뇨·흡연자는 <strong>3~4개월</strong>.</p>' ),
		array( '구강검진', 'prevention', '정기 구강 종합 검사', '<p>Oral Examination. 시진·촉진·X-ray. <strong>충치·치주염·구강암 조기 발견</strong>.</p>' ),
		array( '우식 위험도 평가', 'prevention', '개인별 충치 위험 등급 산정', '<p>Caries Risk Assessment. 식습관·타액·불소 노출 등 평가. <strong>예방 계획 개별화</strong>.</p>' ),
		array( '타액검사', 'prevention', '침으로 충치 위험 세균 측정', '<p>Saliva Test. <strong>뮤탄스균·락토바실러스 수</strong>·타액 pH·완충 능력 측정.</p>' ),
		array( '치아에 좋은 음식', 'prevention', '치즈·녹차·견과·물', '<p>치즈·<strong>녹차(폴리페놀)</strong>·견과·물. 산성·당 음식 피하기.</p>' ),
		array( '치아에 나쁜 습관', 'prevention', '이갈이·손톱 물기·얼음 씹기', '<p>이갈이·손톱 물기·<strong>얼음·펜 씹기</strong>·강한 산성 음료. 파절·마모 원인.</p>' ),
		array( '올바른 칫솔질 방법', 'prevention', '3·3·3 원칙 + 회전법', '<p><strong>하루 3회·식후 3분·3분 이상</strong>. 잇몸에서 치아 방향으로 회전법(로테이션).</p>' ),
		array( '칫솔질', 'prevention', '충치·치주염 예방의 기본', '<p>Brushing. 하루 <strong>최소 2회 이상</strong>, 자기 전 필수. 부드러운 칫솔 권장.</p>' ),
		array( '치약 성분', 'prevention', '불소·연마제·계면활성제', '<p>주요 성분: <strong>불소(재광화)·연마제·계면활성제·항균제</strong>. 성인은 1000ppm 이상 불소.</p>' ),
		array( '불소', 'prevention', '충치 예방의 핵심 무기물', '<p>Fluoride. <strong>법랑질 강화·재광화·항균</strong>. 치약·물·도포로 공급.</p>' ),
		array( '불소 바니시', 'prevention', '고농도 불소 도포용 바니시', '<p>Fluoride Varnish. <strong>5% NaF</strong>. 도포 후 4시간 음식 금지.</p>' ),
		array( '자일리톨', 'prevention', '충치 예방 효과 있는 대체 감미료', '<p>Xylitol. 뮤탄스균이 <strong>대사하지 못하는 당</strong>. 껌·사탕으로 섭취.</p>' ),
		array( '프로바이오틱스', 'prevention', '유익균으로 구강 건강 개선', '<p>Oral Probiotics. Streptococcus salivarius 등. <strong>구취·치주염 개선</strong> 효과 연구 중.</p>' ),
		array( '혀 클리너', 'prevention', '설태 제거 전용 도구', '<p>Tongue Scraper. 혀 표면 <strong>흰 막(설태) 제거</strong>. 구취 완화.</p>' ),
		array( '구강 세정기', 'prevention', '워터픽 · 수압 청소기', '<p>Water Flosser. 수압으로 <strong>치간·잇몸 라인 청소</strong>. 임플란트·교정에 유용.</p>' ),
		array( '구강 세정제', 'prevention', '살균·불소 함유 가글', '<p>Mouthwash. 클로르헥시딘·불소·염화세틸피리디늄. <strong>양치 보조</strong>.</p>' ),
		array( '엑스레이 (X-ray)', 'prevention', '치아·잇몸뼈·신경 X선 촬영', '<p>파노라마·치근단·교익·CBCT. <strong>극소량 방사선</strong>으로 안전.</p>' ),
		array( '치과 CT (CBCT)', 'prevention', '3D 정밀 진단 CT', '<p>Cone Beam CT. <strong>3D 입체 진단</strong>. 임플란트·매복치·근관에 필수.</p>' ),
		array( '파노라마', 'prevention', '전체 치아·턱뼈 한 장 촬영', '<p>Panorama X-ray. 상하악 <strong>전체를 한 장</strong>에 촬영. 사랑니·전체 구조 확인.</p>' ),
		array( '파노라마 X선', 'prevention', '파노라마와 동일', '<p>파노라마 X-ray. 전체 치아·턱관절 개관.</p>' ),
		array( '파노라마 촬영', 'prevention', '전체 X-ray 촬영 과정', '<p>10초 이내 촬영. 서 있거나 앉아서 진행. <strong>얼굴을 고정</strong>하고 정지.</p>' ),
		array( '세팔로 X선', 'prevention', '옆얼굴 X-ray · 교정 진단', '<p>Cephalometric. 교정 진단 필수. <strong>골격·치아·연조직 각도</strong> 측정.</p>' ),
		array( '방사선 안전', 'prevention', '치과 X-ray의 극소량 안전성', '<p>디지털 X-ray는 <strong>필름 대비 1/4~1/10</strong> 방사선. 안전.</p>' ),
		array( '방사선 방어', 'prevention', '납 앞치마·갑상선 보호대', '<p>Lead Apron·Thyroid Collar. <strong>모든 촬영 시 착용</strong>. 임산부·소아 필수.</p>' ),
		array( '방사선량', 'prevention', '치과 X-ray의 극소량', '<p>파노라마 1회 = <strong>비행기 3~5시간</strong> 우주선. 극도로 안전.</p>' ),
		array( '치아 번호 체계', 'prevention', 'FDI·유니버설·파머 표기법', '<p>FDI(11~48 국제표준)·<strong>Universal(1~32 미국)</strong>·Palmer(사분면 표기).</p>' ),
		array( '치아 색상 (셰이드)', 'prevention', 'A1~D4 표준 등급', '<p>Vita Shade Guide. <strong>A1이 가장 밝고 D4가 가장 어두움</strong>.</p>' ),

		/* ==================== 일반·해부·마취·병원 운영 (추가) ==================== */
		array( '치아 번호', 'general', 'FDI 국제 표기법 (11~48)', '<p>FDI 시스템. 상악 우측(1사분면) → 상악 좌측(2) → 하악 좌측(3) → 하악 우측(4). <strong>사분면·번호 조합</strong>.</p>' ),
		array( '치식 (표기법)', 'general', '치아 위치 국제 표기법', '<p>Dental Notation. FDI 대표. <strong>11~48 두 자리 숫자</strong>로 32개 치아 표시.</p>' ),
		array( '치아 발육 단계', 'general', '개시기→종상기→관상기→뿌리 형성기', '<p>Tooth Development. <strong>배아 6주부터 시작</strong>. 유치 6개월~2.5세 맹출, 영구치 6세~.</p>' ),
		array( '치아 맹출', 'general', '치아가 잇몸을 뚫고 나오는 과정', '<p>Eruption. 유치 6개월~2.5세, 영구치 6~13세, 사랑니 17~25세.</p>' ),
		array( '맹출', 'general', '치아 맹출과 동일', '<p>치아가 나오는 과정. <strong>맹출 지연</strong> 시 X-ray 확인.</p>' ),
		array( '유치', 'general', '어린이의 젖니 · 총 20개', '<p>Primary Teeth. <strong>6개월~2.5세 맹출, 6~12세 영구치로 교체</strong>.</p>' ),
	    array( '영구치', 'general', '평생 사용하는 성인 치아 · 총 28~32개', '<p>Permanent Teeth. <strong>6세부터 유치와 교체</strong>. 사랑니 포함 최대 32개.</p>' ),
		array( '어금니', 'general', '큰어금니(대구치)와 작은어금니(소구치)', '<p>Molar & Premolar. 음식을 <strong>부수고 갈아내는</strong> 역할.</p>' ),
		array( '앞니', 'general', '중절치·측절치 총 8개', '<p>Incisor. 음식 <strong>자르는 역할</strong>. 얼굴 인상 결정.</p>' ),
		array( '견치', 'general', '송곳니와 동일', '<p>Canine. 뾰족한 <strong>4번째 치아</strong>. 안모 형성·저작 지지.</p>' ),
		array( '소구치', 'general', '작은어금니 총 8개', '<p>Premolar. 어금니 중 작은 것. <strong>발치 교정</strong> 시 자주 뽑힘.</p>' ),
		array( '치관', 'general', '잇몸 위 치아 부분', '<p>Crown. <strong>잇몸 밖으로 노출된 치아</strong>. 법랑질로 덮임.</p>' ),
		array( '치근', 'general', '잇몸 속 치아 뿌리', '<p>Root. 잇몸 속 뿌리. <strong>치조골에 고정</strong>.</p>' ),
		array( '치수', 'general', '치아 내부 신경·혈관', '<p>Pulp. 신경·혈관·결합조직. <strong>치수염 → 신경치료</strong>.</p>' ),
		array( '상아질', 'general', '법랑질 아래 노란 조직', '<p>Dentin. 치아의 대부분. <strong>노란색</strong>. 자극 전달 (시린 원인).</p>' ),
		array( '법랑질', 'general', '치아 표면의 가장 단단한 조직', '<p>Enamel. 인체에서 <strong>가장 단단</strong>. 96% 무기질. 재생 안 됨.</p>' ),
		array( '백악질', 'general', '치근 표면의 얇은 조직', '<p>Cementum. 시멘트질. <strong>치주인대와 치조골 연결</strong>.</p>' ),
		array( '치조골', 'general', '치아를 지탱하는 턱뼈 부분', '<p>Alveolar Bone. <strong>치아 뿌리를 감싸는 턱뼈</strong>. 발치 후 흡수.</p>' ),
		array( '교두', 'general', '어금니 씹는 면의 돌출부', '<p>Cusp. 어금니 씹는 면의 <strong>4~5개 뾰족한 돌출</strong>. 저작 담당.</p>' ),
		array( '협면', 'general', '치아의 볼 쪽 면', '<p>Buccal Surface. 어금니의 <strong>볼 쪽 면</strong>. 청소 소홀 부위.</p>' ),
		array( '설면', 'general', '치아의 혀 쪽 면', '<p>Lingual Surface. 하악 치아의 <strong>혀 쪽 면</strong>. 상악은 구개면(Palatal).</p>' ),
		array( '협측/설측', 'general', '치아 위치 표기 · 볼쪽/혀쪽', '<p>Buccal/Lingual. 치아 5면 중 <strong>볼쪽·혀쪽</strong> 방향.</p>' ),
		array( '치아 균열 증후군', 'general', '미세 균열로 인한 씹기 통증', '<p>Cracked Tooth Syndrome. <strong>씹을 때만 예리한 통증</strong>. 조기 진단 어려움.</p>' ),
		array( '치아 과민증', 'general', '차가운·뜨거운 자극에 시린 증상', '<p>Dentin Hypersensitivity. <strong>상아질 노출</strong> 원인. 시린이 치약·불소도포·레진.</p>' ),
		array( '치아 흔들림', 'general', '치주염·외상·과부하로 흔들리는 치아', '<p>Mobility. <strong>0~3도 분류</strong>. 원인별 스플린트·치주치료·발치.</p>' ),

		/* ==================== 마취·진정 ==================== */
		array( '마취', 'surgery', '치과 진료 시 통증 감소', '<p>Anesthesia. <strong>표면·침윤·전달 마취</strong>. 통증 없이 시술 가능.</p>' ),
		array( '국소마취', 'surgery', '해당 부위만 마취하는 표준 방식', '<p>Local Anesthesia. <strong>침윤 마취·전달 마취</strong>. 리도카인·아르티카인 대표.</p>' ),
		array( '침윤마취', 'surgery', '치아 주변에 직접 마취제 주입', '<p>Infiltration. 잇몸에 <strong>직접 주사</strong>. 상악 치아에 주로 사용.</p>' ),
		array( '전달마취', 'surgery', '신경 다발에 마취제로 광범위 마취', '<p>Nerve Block. 하악 어금니 부위 <strong>하치조 신경 전달</strong> 마취 대표.</p>' ),
		array( '아산화질소', 'surgery', '웃음가스 · 흡입 진정', '<p>Nitrous Oxide. <strong>소아·공포증 환자용</strong> 흡입 진정. 안전.</p>' ),
		array( '수면 진정', 'surgery', '경구·정맥 진정제로 편안한 상태', '<p>IV/Oral Sedation. 완전 수면 아닌 <strong>깊은 이완 상태</strong>. 사랑니·임플란트에 활용.</p>' ),
		array( '진정 치료', 'surgery', '수면 진정과 동일', '<p>Sedation. 불안·공포 환자용 <strong>이완 유도</strong>.</p>' ),

		/* ==================== 재료·장비 ==================== */
		array( '티타늄', 'general', '임플란트 표준 소재 · 생체친화적', '<p>Titanium. <strong>알레르기 거의 없음·가벼움·강함·골유착</strong>. 임플란트 표준.</p>' ),
		array( '핸드피스', 'general', '치과 회전 기구 통칭 · 드릴', '<p>Handpiece. 고속·저속. 충치 제거·치아 삭제·연마에 사용.</p>' ),
		array( '치과용 레이저', 'general', '레이저 기반 정밀 시술 장비', '<p>Dental Laser. 물방울 레이저(Er:YAG)·다이오드. <strong>통증·출혈 최소, 살균</strong> 효과.</p>' ),
		array( 'Er:YAG 레이저', 'general', '경조직·연조직 모두 사용 가능', '<p>Erbium YAG. <strong>충치 제거·치석·잇몸 수술</strong>. 물방울 레이저 대표.</p>' ),
		array( '다이오드 레이저', 'general', '잇몸·연조직 시술용 레이저', '<p>Diode Laser. <strong>잇몸 성형·미백·구내염</strong>에 사용. 소형.</p>' ),
		array( '광중합기', 'general', '레진 경화용 파란 광 장치', '<p>Curing Light. LED로 <strong>레진 20초 이내 경화</strong>.</p>' ),
		array( '치과용 현미경', 'general', '정밀 시술용 확대 장비', '<p>Dental Microscope. 신경치료·미세 시술에 <strong>4~20배 확대</strong>.</p>' ),
		array( '마이크로스코프', 'general', '치과용 현미경과 동일', '<p>정밀 신경치료·심미치료·미세 수술에 사용.</p>' ),
		array( '미세현미경', 'general', '마이크로스코프와 동일', '<p>정밀 확대 시야로 <strong>미세한 병소·파일 파절 확인</strong>.</p>' ),
		array( '인트라오럴 카메라', 'general', '입안 상태를 화면으로 보여줌', '<p>Intraoral Camera. <strong>환자에게 실시간 구강 상태</strong> 보여주며 상담.</p>' ),
		array( '구강 스캐너', 'general', '입안을 3D 디지털로 스캔', '<p>iTero·TRIOS·PrimeScan. 인상재 없이 <strong>3D 데이터</strong> 확보.</p>' ),
		array( '3D 프린팅', 'general', '치과 모형·가이드·임시 크라운 제작', '<p>Dental 3D Printing. <strong>수술 가이드·임시 크라운·투명 리테이너</strong> 제작.</p>' ),
		array( '3D 프린팅 치과', 'general', '3D 프린팅 활용 치과', '<p>디지털 워크플로우의 핵심. <strong>제작 속도·정확도</strong> 향상.</p>' ),
		array( '디지털 워크플로우', 'general', 'CBCT+스캔+CAD/CAM 통합', '<p>Digital Workflow. <strong>진단부터 보철·수술 가이드</strong>까지 디지털 처리.</p>' ),
		array( '디지털 보철', 'general', 'CAD/CAM 기반 보철 제작', '<p>Digital Prosthetics. 구강 스캔 → PC 설계 → <strong>밀링 자동 제작</strong>. 정밀·재현성 우수.</p>' ),
		array( '디지털 임플란트', 'general', '디지털 워크플로우 기반 임플란트', '<p>CBCT·구강스캔·가이드 수술. <strong>수술 정밀도·환자 편의</strong> 향상.</p>' ),
		array( '디지털 진단 모형', 'general', 'PC로 확인·저장하는 3D 모형', '<p>Digital Model. 석고 모형 대신 <strong>디지털 저장·분석</strong>.</p>' ),
		array( '셀렉 (CEREC)', 'general', '당일 세라믹 보철 시스템', '<p>CEREC. 구강 스캔 → 즉시 CAD/CAM 밀링 → <strong>당일 크라운 완성</strong>.</p>' ),
		array( 'CAD/CAM 당일 보철', 'general', '방문 당일 보철 완성', '<p>1회 방문에 크라운·인레이 완성. <strong>임시치아 불필요</strong>.</p>' ),
		array( 'AI 영상 판독', 'general', '치과 X-ray AI 자동 판독', '<p>Dental AI. 파노라마·CBCT를 AI가 분석해 <strong>충치·낭종·문제 감지</strong>.</p>' ),
		array( '압전 수술기', 'general', '초음파 진동으로 정밀 뼈 절제', '<p>Piezosurgery. <strong>초음파로 뼈만 선택 절제</strong>. 신경·혈관 안전. 상악동 거상 등.</p>' ),
		array( '회전 기구', 'general', '핸드피스에 장착하는 회전 도구', '<p>Rotary Instrument. 다이아몬드·카바이드 버. 충치 제거·치아 삭제.</p>' ),
		array( '니켈타이타늄 파일', 'general', 'NiTi 파일과 동일', '<p>Ni-Ti File. 신경치료용 회전 파일. <strong>곡선 신경관</strong> 안전 세척.</p>' ),

		/* ==================== 임신·전신 건강 ==================== */
		array( '임신 중 치과치료', 'general', '임신 시기별 안전 치료 가이드', '<p>Pregnancy Dentistry. <strong>2삼분기(4~6개월)</strong>가 가장 안전. 응급은 어느 시기든 가능.</p>' ),
		array( '임신성 치은염', 'general', '임신 중 심해지는 잇몸 염증', '<p>Pregnancy Gingivitis. 호르몬 변화로 <strong>잇몸 예민·출혈</strong>. 스케일링·구강위생.</p>' ),
		array( '호르몬과 치과', 'general', '여성 호르몬 변화의 구강 영향', '<p>사춘기·임신·폐경기 호르몬 변화가 <strong>잇몸·구강 건강</strong>에 영향.</p>' ),
		array( '폐경기 구강건조', 'general', '폐경 호르몬 변화로 침 감소', '<p>Menopausal Xerostomia. 에스트로겐 감소로 <strong>침 분비 감소</strong>. 관리 필요.</p>' ),
		array( '심혈관 환자 치과', 'general', '심장 질환 환자 진료 주의', '<p>Cardiac Patient Dental Care. <strong>사전 항생제·혈압 모니터링·응급 대비</strong>.</p>' ),
		array( '당뇨 환자 치과', 'general', '당뇨 환자 진료 주의사항', '<p>Diabetic Dental Care. <strong>혈당 확인·감염 위험 관리</strong>. 임플란트 가능.</p>' ),
		array( '당뇨 환자 구강 관리', 'general', '당뇨는 치주염 위험 증가', '<p>혈당 조절이 <strong>치주염 예방의 첫 걸음</strong>. 3~4개월 정기 관리.</p>' ),
		array( '골다공증 환자 치과', 'general', '비스포스포네이트 복용자 주의', '<p>Osteoporosis Dental. 발치 시 <strong>BRONJ 위험</strong>. 사전 상담 필수.</p>' ),
		array( '항응고제와 치과', 'general', '와파린·아스피린 복용자 발치 주의', '<p>Anticoagulants. <strong>INR 확인·복용 유지·지혈 준비</strong>. 임의 중단 위험.</p>' ),
		array( '항암치료 환자 치과', 'general', '항암 시기 구강 관리', '<p>Cancer Dental. <strong>구내염·구강 건조·감염</strong> 위험. 항암 전 발치·치료 완료 권장.</p>' ),
		array( '흡연과 구강 건강', 'general', '흡연은 치주염·구강암·임플란트 실패 원인', '<p>Smoking. <strong>임플란트 실패율 2~3배</strong>·구강암·치주염·구취.</p>' ),
		array( '치약 성분 (불소)', 'general', '성인 1000ppm 이상 불소 권장', '<p>Fluoride Toothpaste. 성인 <strong>1000~1500ppm</strong>. 소아 500ppm.</p>' ),

		/* ==================== 병원 운영·행정 ==================== */
		array( '치과 비용', 'general', '보험·비급여 진료비', '<p>보험(급여) vs 비급여. <strong>건강보험 적용 치료·비급여 비용</strong> 사전 상담 권장.</p>' ),
		array( '건강보험 적용 치료', 'general', '보험 적용 대상 치과 진료', '<p>스케일링(연1회)·<strong>충치치료·신경치료·발치·65+ 임플란트 2개</strong>·전악 틀니.</p>' ),
		array( '스케일링 건강보험', 'general', '만 19세 이상 연 1회 적용', '<p>1월 1일 갱신. 본인부담 약 <strong>25,000원</strong>. 예방적 관리에 유용.</p>' ),
		array( '임플란트 건강보험', 'general', '만 65세 이상 평생 2개', '<p>본인부담 약 30%. <strong>부분 무치악·PFM/지르코니아</strong> 크라운.</p>' ),
		array( '치과 산정특례', 'general', '중증 질환 본인부담 감면', '<p>중증 구강암 등 <strong>본인부담 5%</strong> 산정특례. 등록 필요.</p>' ),
		array( '치과 본인부담금', 'general', '보험 적용 시 환자 부담분', '<p>일반 30%·시니어 감면 등. <strong>병원별 비급여 가격</strong>은 자율.</p>' ),
		array( '노인 임플란트 보험', 'general', '만 65세 이상 평생 2개', '<p>부분 무치악만. <strong>본인부담 30%</strong>.</p>' ),
		array( '치아 보험', 'general', '민간 치과 보험 상품', '<p>Dental Insurance. 임플란트·크라운·틀니 비용 부담 완화. <strong>가입 조건·대기 기간</strong> 확인.</p>' ),
		array( '실비보험 청구', 'general', '치과 진료 실손보험 청구', '<p>실손·<strong>치과 특약</strong>으로 비급여 청구 가능. 영수증·진료 확인서 필요.</p>' ),
		array( '의료비 세액공제', 'general', '연말정산 시 치과 진료비 공제', '<p>연 250만원 초과분 <strong>15% 세액공제</strong>. 임플란트·라미네이트도 대상.</p>' ),
		array( '비급여 동의서', 'general', '비급여 진료 전 서면 동의', '<p>비급여 치료 시 <strong>비용·내용 서면 동의</strong> 필수 (의료법).</p>' ),
		array( '진료 기록 발급', 'general', '진료 확인서·차트 발급', '<p>환자 요청 시 <strong>진료 기록·영수증·소견서</strong> 발급 (개인정보 보호법).</p>' ),
		array( '치료 동의서', 'general', '침습적 치료 전 서면 동의', '<p>Informed Consent. <strong>치료 방법·부작용·비용</strong> 설명 후 서면 동의.</p>' ),
		array( '치료 계획', 'general', '진단 후 세우는 종합 치료 계획', '<p>Treatment Plan. 진단·<strong>우선순위·기간·비용</strong> 종합. 환자와 협의.</p>' ),
		array( '첫 상담', 'general', '초진 상담 절차', '<p>First Consultation. 문진·X-ray·구강 검사·<strong>상담·치료 계획</strong>. 30~60분.</p>' ),
		array( '비용 상담', 'general', '치료비 상세 안내', '<p>Cost Consultation. <strong>단계별 비용·건강보험·할부</strong> 안내.</p>' ),
		array( '치과 보증서', 'general', '보철·임플란트 보증 기간', '<p>Warranty. 임플란트 5~10년, 크라운 2~5년. <strong>병원별 보증 정책</strong> 다름.</p>' ),
		array( '2차 의견 (세컨드 오피니언)', 'general', '다른 치과에서 재검토', '<p>Second Opinion. 큰 치료 전 <strong>2~3곳 상담</strong>. 신뢰할 만한 결정에 도움.</p>' ),
		array( '리콜 시스템', 'general', '정기 검진 안내 시스템', '<p>Recall System. 6개월 주기 <strong>정기 검진 안내</strong>. SMS·전화·앱.</p>' ),
		array( '환자 경험', 'general', '환자 만족도·서비스 품질', '<p>Patient Experience. 진료 외 <strong>대기·상담·A/S</strong> 종합 경험.</p>' ),
		array( '환자 교육 프로그램', 'general', '구강 관리 교육', '<p>Patient Education. <strong>양치·치실·식습관·정기 검진</strong> 안내.</p>' ),
		array( '치과 공포증', 'general', '치과 진료 극도 두려움', '<p>Dental Phobia. <strong>진정요법·행동조절·점진 노출</strong>로 극복.</p>' ),
		array( '치과 포비아 극복법', 'general', '점진 노출·진정·상담', '<p>Overcoming Phobia. <strong>친절한 상담·짧은 시술·진정요법</strong>. 신뢰 형성이 핵심.</p>' ),
		array( '노인 구강 관리', 'general', '시니어 특화 구강 관리', '<p>Geriatric Dentistry. <strong>구강 건조·뿌리 우식·틀니 관리·의치 적응</strong>.</p>' ),
		array( '노인 구강건조증', 'general', '노화·약물로 침 감소', '<p>Xerostomia in Elderly. 약물·<strong>노화</strong>가 주 원인. 수분 섭취·타액 대체제.</p>' ),
		array( '노인 연하장애', 'general', '노인의 음식 삼킴 어려움', '<p>Dysphagia in Elderly. <strong>발음·삼킴 재활</strong>. 치과·재활의학 협진.</p>' ),
		array( '구강 건조증', 'general', '침 분비 감소로 구강 문제 증가', '<p>Xerostomia. <strong>충치·구내염·구취</strong> 위험 증가.</p>' ),
		array( '구강 칸디다증', 'general', '입안 곰팡이 감염', '<p>Oral Candidiasis. <strong>흰 막·붉은 궤양</strong>. 항진균제로 치료.</p>' ),
		array( '구취', 'general', '입냄새와 동일', '<p>Halitosis. 원인 다양: <strong>치주염·설태·충치·구강 건조·소화기</strong>.</p>' ),
		array( '구취 원인과 관리', 'general', '치과·소화기·전신 원인', '<p>80% 이상 구강 원인. <strong>스케일링·설태·구강 관리</strong>로 개선.</p>' ),
		array( '설태', 'general', '혀 표면 흰 막', '<p>혀 유두 사이 <strong>세균·음식물</strong>. 구취 주 원인. 혀 클리너.</p>' ),
		array( '치의학 전문의', 'general', '11개 세부 전문의 제도', '<p>보철·교정·보존·치주·구강외과·소아·구강내과·영상·구강병리·<strong>통합치의학·예방</strong>.</p>' ),
		array( '치과 전문의 제도', 'general', '치의학 전문의 자격', '<p>일반의 → <strong>3년 인턴/레지던트 → 전문의 시험</strong>. 세부 11과.</p>' ),
		array( '통합치의학과', 'general', '전 진료 영역 종합 관리 전문의', '<p>Integrated Dentistry. <strong>일차 진료·종합 치료 계획</strong> 담당.</p>' ),
		array( '치과 위생사', 'general', '스케일링·예방 국가자격', '<p>Dental Hygienist. <strong>스케일링·구강교육·불소 도포</strong>.</p>' ),
		array( '치과 응급', 'general', '즉시 처치가 필요한 상황', '<p>완전 탈구·심한 부기·<strong>출혈·심한 통증</strong>. 즉시 응급실 or 야간 치과.</p>' ),
		array( '수술 후 구강 관리', 'general', '발치·수술 후 회복 관리', '<p>부드러운 음식·<strong>강한 헹굼 금지·항생제·냉찜질</strong>.</p>' ),
		array( '합병증', 'general', '치과 시술 후 발생 가능한 문제', '<p>감염·출혈·<strong>신경 손상·상악동 침범·드라이 소켓</strong>. 정기 검진으로 조기 발견.</p>' ),
		array( '금기증', 'general', '치료를 시행할 수 없는 조건', '<p>Contraindication. <strong>임신 초기·특정 약물 복용·심한 전신질환</strong> 등 케이스별.</p>' ),
		array( '적응증', 'general', '해당 치료가 필요한 조건', '<p>Indication. 각 치료의 <strong>적용 대상·조건</strong>. 진단으로 결정.</p>' ),
		array( '예후', 'general', '치료 후 예상되는 경과', '<p>Prognosis. 좋음·보통·나쁨. <strong>환자·병소 조건·치료법</strong>에 따라 다름.</p>' ),
		array( '약물 상호작용', 'general', '치과 약물과 복용약 간섭', '<p>항생제·진통제·마취제 상호작용. <strong>복용약 사전 알림</strong>.</p>' ),
		array( '예방적 항생제', 'general', '수술 전 감염 예방 투여', '<p>Antibiotic Prophylaxis. <strong>심장 판막·인공 관절</strong> 환자 필요.</p>' ),
		array( '치과 항생제', 'general', '감염·수술 시 처방', '<p>Amoxicillin·Clindamycin 대표. <strong>임의 중단 금지</strong>.</p>' ),
		array( '진정 치료', 'general', '수면 진정과 동일', '<p>Sedation. 정맥·경구·흡입. <strong>의식 있는 상태의 이완</strong>.</p>' ),
		array( '의료법', 'general', '의료 행위의 법적 근거', '<p>Medical Law. <strong>진료·비급여·개인정보·의료기관 운영</strong> 등 규정.</p>' ),
		array( '환자 불만 처리', 'general', '병원 컴플레인 대응 절차', '<p>Complaint Handling. <strong>경청·조사·해결·개선</strong>. 서비스 품질 향상.</p>' ),
		array( '치과 의료 분쟁', 'general', '진료 결과 분쟁 대응', '<p>Dental Dispute. 한국의료분쟁조정중재원 또는 소송. <strong>기록·동의서·소통</strong>이 핵심.</p>' ),
		array( '외국인 환자 진료', 'general', '외국인 대상 치과 진료', '<p>International Patient. <strong>영어·중국어·일본어</strong> 지원. 관광 치과 인기.</p>' ),
		array( '의료관광 치과', 'general', '해외 환자 대상 치과 진료', '<p>Medical Tourism. <strong>임플란트·심미치료</strong> 인기. 국제 진료 코디네이터.</p>' ),
		array( '영문 진료기록', 'general', '외국 환자용 영문 차트', '<p>English Dental Record. <strong>보험·비자·항공 등</strong> 사용. 요청 발급.</p>' ),
		array( '워킹인 진료', 'general', '예약 없이 방문 진료', '<p>Walk-in. <strong>당일 예약 없이 방문</strong>. 응급·단순 진료에 활용.</p>' ),
	);
}

/**
 * v3.35.2 · 대량 확장 시드 마이그레이션 (한 번만 실행)
 */
// v3.37.0 · admin_init로 이동
add_action( 'admin_init', function() {
	if ( get_option( 'moondental_encyclopedia_v3352_expand' ) === 'done' ) return;
	if ( ! post_type_exists( 'md_term' ) ) return;

	$data = moondental_encyclopedia_seed_data_v3352();

	foreach ( $data as $t ) {
		list( $title, $cat, $excerpt, $body ) = $t;

		// 중복 스킵
		$existing = get_posts( array(
			'post_type'      => 'md_term',
			'title'          => $title,
			'posts_per_page' => 1,
			'post_status'    => 'any',
			'fields'         => 'ids',
			'no_found_rows'  => true,
		) );
		if ( ! empty( $existing ) ) continue;

		$post_id = wp_insert_post( array(
			'post_type'    => 'md_term',
			'post_status'  => 'publish',
			'post_title'   => $title,
			'post_excerpt' => $excerpt,
			'post_content' => $body,
			'post_name'    => sanitize_title( $title ),
		) );
		if ( $post_id && ! is_wp_error( $post_id ) ) {
			$term = get_term_by( 'slug', $cat, 'md_term_category' );
			if ( $term ) {
				wp_set_object_terms( $post_id, array( $term->term_id ), 'md_term_category' );
			}
		}
	}

	update_option( 'moondental_encyclopedia_v3352_expand', 'done' );
}, 40 );
